<?php
return [
    'app_name' => 'Fan Rating',
    'frontend_url' => 'https://fanratingweb.com',
    'admin_email' => 'admin@fanratingweb.com',
    'sender_email' => 'admin@fanratingweb.com',
    'user.passwordResetTokenExpire' => 3600,
    'user.passwordMinLength' => 8,
    'dateformat' => 'd M Y',
    'pageSize' => 10,
    'football_api_key' => '891bb7dd34ee7a80b5694a36ee5f7891',
    'football_api_host' => 'v3.football.api-sports.io',
    'digital_o_key' => 'B4SRUEEU5XJDHJSWKXQF',
    'digital_o_secret' => '665mNYXDcus7dngmIf++Qu8fbpvN0j/hOKucbhZ39/Q',
    'push_api_key' => 'AAAA8OLfUIo:APA91bH_4gIO7ACrzQx3zdCrtiBx_csXpY6N_fm8N-wnznHp_Q6MsC8ksNFG9R48rWwjOpOfgjT4VXrcwUyoEm-zhKce5DLzbqmglIyY3ApfMNMKrhBSs5Z0sROPKT8N6XFMPEBr1Uq9',
    //  'stripe_pub_key' => 'pk_test_51JDokBBoivOMTJu4orcCGr1EBc0w3PLdbQmnhvVlwZwVdZKR6QZZljK4BbKYEGARD8PVOxqrJoDfSxipE2ThOQJo00ELIEf1oY',
    //  'stripe_sec_key' => 'sk_test_51JDokBBoivOMTJu4atDBUHHVjijus9sfFEc7riDlNjvwXhrISqDbBIeNArXuGcK2AhjXdGk30IwTAe09jeEcpKoh00ylRL2rMd',
    'stripe_pub_key' => 'pk_live_51JDokBBoivOMTJu4J4CGTBNkorqxtHZWSX37JoKHcRFoPxHbVTREySVozU0mBalb7aXjUlYQHkkHytXbky52cwRF00o5pygToE',
    'stripe_sec_key' => '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',
    'timezone' => 'Europe/Rome',
];