export const ArLanguage = {
    TEAMLIST_TITLE: "اختر فريقك",
    NOTIFICATION: "إشعار",
    TEAMLIST_DESC:
        "Remember that you will not be able to change it anymore, it will be the only team you vote for",
    TEAMLIST_DESC2: "for free and on which you will receive news",
    NEXT: "التالي",
    TIFA: "تيفا",
    RATE_IT: "قيمها",
    WIN: "ينتصر",
    ALL: "الكل",
    CURRENT: "Curالحاليrent",
    PAST: "ماضي",
    RATE: "معدل",
    VOTE: "تصويت",
    VIEW: "رأي",
    ACHIEVEMENTS: "إنجازات",
    PRIME_AMAZON: "برايم أمازون",
    PARTNERS_PRIZES: "جوائز الشركاء",
    LIMITED_AVAILABILITY: "التوفر المحدود",
    VIEW_ALL: "مشاهدة الكل",
    FORGOT_PASSWORD: "هل نسيت كلمة السر؟",
    Forgot_Password: "هل نسيت كلمة السر؟",
    NEW_PASSWORD: "كلمة السر الجديدة",
    CONFIRM_NEW_PASSWORD: "تأكيد كلمة المرور الجديدة",
    SAVE_PASSWORD: "حفظ كلمة المرور",
    LOGIN: "Login",
    EDIT_PROFILE: "تعديل الملف الشخصي",
    SIGN_OUT: "خروج",
    SIGN_IN: "Sign In",
    SIGN_IN_CAPITAL: "SIGN IN",
    SIGN_UP: "Sign Up",
    SIGN_UP_CAPITAL: "SIGN UP",
    TOKEN: "رمز",
    POINTS: "نقاط",
    EMAIL: "البريد الإلكتروني",
    PASSWORD: "كلمة المرور",
    OR: "أو",
    SIGN_IN_WITH_FACEBOOK: "Sign In with Facebook",
    SIGN_IN_WITH_GOOGLE: "Sign In with Google",
    SIGN_Up_WITH_FACEBOOK: "Sign Up with Facebook",
    SIGN_Up_WITH_GOOGLE: "Sign Up with Google",
    NO_ACCOUNT: `Don't have an account?`,
    HAVE_ACCOUNT: "Already have an account?",
    FIRST_NAME: "الاسم الاول",
    LAST_NAME: "الكنية",
    GENDER: "جنس",
    DATE_OF_BIRTH: "تاريخ الولادة",
    USERNAME: "اسم المستخدم",
    CREATE_ACCOUNT: "Create Account",
    SIGN_IN_WITH_APPLE: "Sign In with Apple",
    SIGN_UP_WITH_FACEBOOK: "Sign up with Facebook",
    SIGN_UP_WITH_GOOGLE: "Sign up with Google",
    SIGN_UP_WITH_APPLE: "Sign Up with Apple",
    MALE: "Male",
    FEMALE: "Female",
    OTHER: "Other",
    THANK_YOU_FOR_SUBMITTING: "شكرا لك على التقديم",
    PASSWORD_CHANGE_SUCCESSFUL: "تم تغيير كلمة المرور بنجاح",
    PREVIOUS: "سابق",
    SUBMIT: "يُقدِّم",
    FINISH: "إنهاء",
    SKIP: "يتخطى",
    QUIZ_INSTRUCTIONS: "تعليمات الاختبار",
    QUIZ_RESULT: "نتيجة الاختبار",
    YOUR_SCORE: "درجاتك",
    EARNED_TOKENS: "الرموز المكتسبة",
    CLOSE: "قريب",
    FISCAL_CODE: "قانون المالية العامة",
    EDUCATION: "تعليم",
    CITY: "مدينة",
    JOB_LEVEL: "مستوى الوظيفة",
    SAVE_PROFILE: "احفظ الملف",
    PROFILE: "الملف الشخصي",
    CHANGE_PASSWORD: "غير كلمة السر",
    CHEERS: "في صحتك",
    STREAMS: "تدفقات",
    FAN_RATING_TV: "تلفزيون FAN RATING",
    NEWS: "الإخبارية",
    FILTER_BY: "مصنف بواسطة",
    PRIVACY_POLICY: "سياسة الخصوصية",
    TERMS_AND_CONDITION: "الشروط والأحكام",
    MISSION: "Mission",
    HELP: "مساعدة",
    CONTACT_US: "اتصل بنا",
    RANKING: "تصنيف",
    BUY_PACKAGE: "Buy Package",
    THANK_YOU_FOR_REVIEW: "THANK YOU FOR REVIEW",
    THANK_YOU_FOR_VOTING:
        "Thanks for submitting! Your score will be available in 24h from the end of the match. Wait for it!",
    COUNTRY: "Country",
    WATCH_ON: "Watch on DAZN",
    GO_TO_SAN_SIRO_STADIUM: "Go to San Siro Stadium",
    GIFT_CARD: "Gift Card",
    DISCOUNT_CODES: "Discount Codes",
    PRIME_SPECIAL: "Prime Special",
    GOALS: "Goals",
    VOTES: "Votes",
    PLAYED_MATCHES: "Played Matches",
    RANK: "Rank",
    DESCRIPTION: "Description",
    NEXT_2: "Next",
    FORGOT_PASSWORD_CAPITAL: "FORGOT PASSWORD?",
    PASSWORD_CHANGE_SUCCESSFULY: "Password change successfully",
    YOUR_PROFILE: "ملفك الشخصي",
    GOAL: "Goal",
    AVERAGE_FAN_RATING: "Average Fan Rating",
    ACCEPT_TERMS_AND_CONDITION: "Accept terms and condition",
    CONGRATULATION: "Congratualation",
    YOUR_RATE_CARD: "Your Rate Card",
    REDEEM_FOR_TOKENS: "Redeem for Tokens",
    LIVE: "Live",
    POSTED_ON: "Posted on",
    MESSAGE: "Message",
    IN_PROGRESS: "في تَقَدم",
    CONCLUDED: "هو اتمم",
    Look_at_all: "Look at all",
    Share_review: "Share The Pagella with your Friends",
    Find_out: "Find out if you won between",
    remaining: "remaining",
    how_to_play: "كيف ألعب؟",
    ABOUT_US: "من نحن",
    MY_TEAM: "فريقي",
    FAN: "Fan",
    TV_SUBSCRIBER: "TV subscriber",
    STADIUM_SUBSCRIBER: "Stadium subscriber",
    OCCASIONAL: "Occasional",
    YES_LETS_START_CHEERING: "Yes, let's start cheering",
    NO_I_WANT_TO_CHANGE: "No, I want to change",
    PROFESSION: "Profession",
    UPLOAD_A_PHOTO: "UPLOAD A PHOTO",
    SAVE_PHOTO: "Save photo",
    GAMES_PLAYED: "Games Played",
    NATIONALITY: "Nationality",
    HEIGHT: "Height",
    WEIGHT: "Weight",
    I_AM_18_YEARS_OLD: "I am 13 years old",
    REQUIRED_TO_MAKE_IN_APP_PURCHASES_AND_ACCESS_THE_REWARDS_CATALOG:
        "Required to make in app purchases and access the rewards catalog.",
    SELECT_YOUR_HEART_TEAM: "Select your heart team",
    QUIZ_CONGRATULATIONS: `Congratulations, you are a Quiz Winner! You answered correctly to all the questions!`,
    QUIZ_TRY_AGAIN: `You have to prepare a little more but don't worry, you can make up for the next quiz!`,
    CONGRATULATIONS: "Congratulations!",
    BETTER_LUCK_NEXT_TIME: "You will be luckier next time",
    INVITE_A_FRIEND_AND_RECEIVE_25_TOKENS:
        "INVITE A FRIEND AND RECEIVE 25 TOKENS",
    INVITE_FRIENDS_DESCRIPTION:
        "You can invite a friend to register on Fan Rating and receive 25 tokens to use as you like. Remember, you will receive the tokens once the user completes the registration via the invitation link.",
    INVITE_A_FRIEND: "Invite a friend",
    INVITE_AND_REFER: "قم بالدعوة والإحالة",
    BUY_TOKENS: "شراء الرموز",
    TOKENS: "Tokens",
    MAKE_A_PAYMENT: "Make a payment",
    TRANSACTION_LIST: "Transaction list",
    YOUR_TOKENS: "Your tokens",
    VOTE_other_matches: "VOTE other matches",
    LIKES: "Likes",
    SURVEY_INSTRUCTIONS: "SURVEY INSTRUCTIONS",
    SURVEY: "SURVEY",
    SURVEY_COMPLETED: "Thank you! Your submission has been received.",
    RESET_PASSWORD: "Reset Password",
    WARNING: "Warning!",
    OOPS: "Oops!",
    ALERT: "Alert!",
    Something_went_wrong: "Something went wrong!",
    SUCCESS: "Success!",
    ENTER_YOUR_EMAIL: "Enter your email",
    ENTER_YOUR_PASSWORD: "Enter your password",
    ENTER_YOUR_FIRST_NAME: "Enter your first name",
    ENTER_VALID_FIRSTNAME: "Please enter valid first name",
    ENTER_YOUR_LAST_NAME: "Enter your last name",
    ENTER_VALID_LASTNAME: "Please enter valid last name",
    ENTER_YOUR_USER_NAME: "Enter your user name",
    ENTER_VALID_USERNAME: "Please enter valid username",
    ENTER_YOUR_DATE_OF_BIRTH: "Enter your date of birth",
    ENTER_YOUR_GENDER: "Enter your gender",
    PLEASE_ACCEPT_TERMS_AND_CONDITIONS: "Please accept terms and conditions",
    PLEASE_SELECT_IF_YOU_ARE_18: "Please select if you are 18",
    PASSWORD_MUST_BE_BETWEEN_8_AND_12: "Password must be of alteast 8 characters",
    BOTH_PASSWORDS_MUST_BE_SAME: "Both passwords must be same",
    PLEASE_ENTER_VALID_EMAIL_ADDRESS: "Please enter valid email address",
    PLEASE_ENTER_VALID_BIRTHDATE: "Please enter valid birthdate",
    SELECT_YOUR_GENDER: "Select your gender",
    SELECT_YOUR_JOB_LEVEL: "Select your job level",
    SELECT_YOUR_EDUCATION: "Select your education",
    SELECT_AN_OPTION: "Select an option",
    SELECT_YOUR_CITY: "Select your city",
    SELECT_YOUR_COUNTRY: "Select your country",
    No_cards: "No Cards Available!",
    Use_default_card: "Use this card as Default",
    CARD_LIST: "CARD LIST",
    ADD_CARD: "ADD",
    Add_New_Card: "Add New Card",
    Pay: "Pay",
    Card_Details: "Card Details",
    ACCEPT_TC: "Accept Terms and Conditions",
    Delete_Message: "Are you sure, you want to delete this card?",
    Logout_Message: "هل أنت متأكد أنك تريد الخروج؟",
    SORRY_NO_DATA_FOUND: "عذرا ، لا توجد بيانات!",
    NAME: "Name",
    REMOVE_ALL_NOTIFICATION: "Are you sure want to remove all notifications?",
    Average_Vote: "Average Vote",
    PLAYER_NAME: "Player Name",
    Players: "Players",
    Substitute: "Substitute",
    Coach: "Coach",
    TO_UNLOCK_MATCH: "TO UNLOCK MATCH",
    BUY_MATCH_BTN_TEXT: "Unlock",
    TOKENS_VALUE: "Tokens",
    SHARE_BTN: "SHARE",
    UNLOCK_MATCH:
        "If you want make more matches for vote you should have to increase your level by gaining more points from the match.",
    INVITE_INFO:
        "Hello, I would like to invite you in FR-PWA application, Please Click on below link and Sign-up your account.",
    LEVEL: "مستوى",
    HURRY_UP_VOTE: "Hurry Up! Votings will close soon!",
    MATCH_RESULTS:
        "Results will be displayed after 24 Hours after match is finished!",
    QUIZ: "QUIZ",
    SELECT_TEAM: "Select Team",
    SELECT_YOUR_TEAM: "Select Your Team",
    CHANGE_TEAM: "فريق التغيير",
    CHOOSE_YOUR_TEAM: "Choose your team",
    INDEX: "INDEX",
    VOTE_FOR_MATCHES: "VOTE FOR MATCHES",
    SOMETHING_WENT_WRONG: "Something went wrong!",
    REMOVE_ALL: "Remove All",
    VERIFICATION_SUCCESS: "Your account has been successfully verified.",
    VERIFICATION_FAILED: "Your account has been rejected.",
    GO: "Go",
    EMAIL_VERIFICATION: "Email Verification",
    WELCOME: "Welcome",
    toFanSerie: "to Fan Rating Serie A!",
    KICK_OFF: "There is little time left for the kick-off",
    WHY_WAIT: "But why wait?",
    CANCEL: "Cancel",
    OK: "OK",
    UPCOMING_MATCH: "UPCOMING MATCH!",
    VOTE_ENABLED: "Votings will be enabled after match has been played.",
    Password_Success: "Password changed successfully!",
    VOTING_CONFIRMATION:
        "Do you want to confirm your ratings for {{TEAMA}} and {{TEAMB}}? You can’t change your ratings after confirmation.",
    WINNERS: "WATCH FAN WINNER",
    VERIFIED: "YOU'RE VERIFIED!",
    NOT_VERIFIED: "YOU'RE NOT VERIFIED!",
    FAQ: "Consult the FAQ",
    HOW_TO_PLAY: "Find out how to play",
    BECOME_TESTER: "Become a tester now",
    SORRY_THIS_PAGE_IS_NOT_AVAILABLE: "Sorry, this page isn't available.",
    THE_LINK_YOU_FOLLOWED_MAY_BE_BROKEN:
        "The link you followed may be broken, or the page may have been removed.",
    GO_BACK_TO_FANRATINGWEB: "Go back to FanRatingWeb",
    CONFIRM_REDEEM:
        "Are you sure you want to redeem {{productName}}? The code will be sent to the email you used during registration",
    GOALKEEPER: "GOALKEEPER",
    DEFENDER: "DEFENDER",
    MIDFIELDER: "MIDFIELDER",
    FORWARD: "FORWARD",
    COACH: "COACH",
    SIGNUP_EMAIL: "Sign up with Email",
    INVITE_AND_EARN: "Invite & Earn",
    ADD_COMMENT: "Add a comment . . .",
    UNLOCK: "UNLOCK",
    PASSWORD_MUST_BE_MINIMUM_OF_8_CHARACTERS:
        "Password must be minimum of 8 characters",
    CHOOSE_FILE: "Choose a file",
    EIGHTEEN_PLUS: "You must be 18+ to proceed!",
    FIRSTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "Firstname should be of atleast 3 letters",
    LASTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "Lastname should be of atleast 3 letters",
    USERNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "Username should be of atleast 3 letters",
    Be_First_to_like: "Be the first to like",
    PROFILE_UPDATED: "Profile picture updated.",
    APPLE_WARN:
        "Do you want to sign in with your old Apple account? Then reset your password.",
    BUY_MORE_TOKENS: "Buy more tokens",
    SELECT_ONE_OPTION: "Please select any one option!",
    VALID_DATE: "Please enter valid date",
    NOT_LEAP_YEAR: "Date entered is not a leap year",
    INVLAID_LEAP_YEAR: "Invalid leap year date",
    INVALID_MONTH: "Invalid Month",
    INVALID_YEAR: "Invalid Year",
    FUTURE_DATE: "You cannot enter future date",
    ALTEAST_EIGHTEEN: "You must be at least 13 years of age",
    AWARD_REDEEMED: "AWARD REDEEMED!",
    CONGRATULATIONS_YOU_JUST_EARNED_A_COIN:
        "Congratulations! you just earned a coin!",
    OFFLINE_TITLE: "You're Offline Mode",
    OFFLINE_SUB_TITLE: "Your app is on offline mode.",
    OFFLINE_DESC: "Try to check your internet connection or wi-fi settings",
    OFFLINE_REFRESH_BTN: "Refresh",
    MATCH: "Match",
    POSITION: "Position",
    FAN_WINNERS: "Fan Winners",
    VOTE_NEW: "Vote",
    DEVICE_INFO1: "Don't know how to install Fan Rating on your device?",
    DESCTOP_INFO1: "Don't know how to install Fan Rating on your device?",
    DEVICE_INFO2: "Find out how, by tapping below",
    DESCTOP_INFO2: "Find out how by clicking below",
    DESCTOP_BTN_NAME: "Click here",
    DEVICE_BTN_NAME: "Tap here",
    NEW_MENU_OPTION: "تثبيت Fan Rating",
    EARNED_MORE_TOKENS:
        "You don't have enough Fan Coins for this award. Earn more or buy them",
    TEASING_ROOM: "Teasing Room",
    TEASING_ROOM_TITLE: "Corner of the Teasing",
    CAPTION: "Caption",
    MEDIA: "Media",
    ADD_POST: "ADD POST",
    READY_TO_SEND: "READY TO SEND?",
    DELETE_POST: "Are you sure you want to delete post?",
    MY_POST: "My post",
    POST_CAPTION: "Enter caption here...",
    REPORT_POST: "Report post",
    REPORT_REASON: "Reason",
    REASON_PLACEHOLDER: "Add reason for report...",
    INCREASE_LEVEL: "ارفع مستواك",
    CHECK_EMAIL:
        "Thank you for redeeming this reward, please check your inbox for your code.",
    ADD_POST_VALIDATION: "Please add Image or Video",
    ADD_CAPTION_VALIDATION: "Add caption",
    NO_COMMENT: "No comments available right now. Be the first to comment.",
    LEVEL_PRICE: "Level Price",
    INCREASE_LEVEL1: "Increase Level",
    ENTER_REPORT: "Please enter reason",
    EDIT_POST: "Edit post",
    UPLOAD_FAILED: "Cannot upload mkv file. Please select mp4/webm",
    COMMENT_SCREEN_TITLE: "Comments",
    MOST_COMMENTS: "Most Comments",
    MOST_LIKES: "Most Likes",
    MOST_RECENT: "Most Recents",
    ORDER_BY: "Order By",
    TEAM_TAG: "Team Tag",
    SELECT_TEAM_TAG: "Select Team Tag",
    FIRST_POST: "What a silence here, make other fans laugh with your first post",
    INVALID_FILE: "Invalid file type",
    UPLOAD_DOCUMENT: "UPLOAD DOCUMENT",
    SAVE_DOCUMENT: "Save Document",
    PLEASE_SELECT_FILE: "Please select file",
    New_Token_key: "Use Token",
    showMore: "Show more",
    reply: "Reply",
    ALL_VIDEOS: "All Videos",
    ALL_NEWS: "All News",
    LIKE: "Like",
    ATTENTION: "Attention!",
    VOTE_ALL_PLAYERS: "Please vote all players",
    WELCOME_BACK_ONBOARD: "Welcome back onboard!",
    SIGN_IN_WITH_EAMIL: "Sign In With Eamil",
    WELCOME_TO_FAN_RATING: "Welcome to Fan Rating",
    BACK: "Back",
    NOT_REGISTERED_YET: "Not registered yet? ",
    CREATE_AN_ACCOUNT: "Create an Account",
    JOIN_THE_COMMUNITY_OF_FOOTBALL_FANS: "Join the community of footballs fans!",

    CONFIRM: "بالتأكيد",
    CONTINUE_VOTE: "قم بتأكيد التصويت",
    NOTE_TWO_TEAMS: "لديك فريقان للتصويت",
    INSTALL_APP_ON_IPHONE: "قم بالتثبيت على Iphone",
    INSTALL_APP_ON_ANDROID: "قم بالتثبيت على Android",

    FAN_COINGS_LEVET_UP_CONFIRM_MESSAGE: "أنت بحاجة إلى {level_price} FanCoins لرفع مستواك ، هل أنت متأكد أنك تريد المتابعة؟",
    FAN_SUBSCRIBER_TV: "تلفزيون المشترك",
    FAN_SEASON_TICKET: "نادي المشتركين",
    FAN_OCCA: "من وقت لآخر",
    PROFILE_UPDATE_MESSAGE: "لقد تغير ملفك الشخصي",
    Phone: "هاتف",
    ENTER_YOUR_PHONE: "أدخل هاتفك.",
    // new words 3/10/2023
    FUN_VERSE: 'FunVerse',
    REGISTER: 'يسجل'
};
