export const ChLanguage = {
    TEAMLIST_TITLE: "选择您的\n球队",
    NOTIFICATION: "通知",
    TEAMLIST_DESC:
        "记住，您将以后无法再改变这球队，它将是你投票给的唯一球队",
    TEAMLIST_DESC2: "免费，您将在上面收到新闻",
    NEXT: "下一个",
    TIFA: "鼓励",
    RATE_IT: "评分",
    WIN: "赢",
    ALL: "全部",
    CURRENT: "当前的",
    PAST: "过去的",
    RATE: "速度",
    VOTE: "投票",
    VIEW: "看法",
    ACHIEVEMENTS: "成就",
    PRIME_AMAZON: "亚马逊会员",
    PARTNERS_PRIZES: "合作伙伴奖",
    LIMITED_AVAILABILITY: "有限的可用性",
    VIEW_ALL: "全部",
    FORGOT_PASSWORD: "忘记密码?",
    Forgot_Password: "忘记密码?",
    NEW_PASSWORD: "新的密码",
    CONFIRM_NEW_PASSWORD: "确认新的密码",
    SAVE_PASSWORD: "保存密码",
    LOGIN: "登录",
    EDIT_PROFILE: "编辑个人资料",
    SIGN_OUT: "登出",
    SIGN_IN: "登出",
    SIGN_IN_CAPITAL: "登出",
    SIGN_UP: "注册",
    SIGN_UP_CAPITAL: "注册",
    TOKEN: "代币",
    POINTS: "积分",
    EMAIL: "电子邮件",
    PASSWORD: "密码",
    OR: "或OR",
    SIGN_IN_WITH_FACEBOOK: "使用Facebook登录",
    SIGN_IN_WITH_GOOGLE: "使用Google登录",
    SIGN_Up_WITH_FACEBOOK: "使用Facebook注册",
    SIGN_Up_WITH_GOOGLE: "使用Facebook注册",
    NO_ACCOUNT: `没有用号`,
    HAVE_ACCOUNT: "已有用户？",
    FIRST_NAME: "名字",
    LAST_NAME: "姓",
    GENDER: "性别",
    DATE_OF_BIRTH: "生日",
    USERNAME: "用户名",
    CREATE_ACCOUNT: "创建账户",
    SIGN_IN_WITH_APPLE: "使用Apple登录",
    SIGN_UP_WITH_FACEBOOK: "使用Faceboo注册",
    SIGN_UP_WITH_GOOGLE: "使用Google注册",
    SIGN_UP_WITH_APPLE: "使用Apple注册",
    MALE: "男",
    FEMALE: "女",
    OTHER: "其他",
    THANK_YOU_FOR_SUBMITTING: "谢谢您的参与",
    PASSWORD_CHANGE_SUCCESSFUL: "成功密码更新",
    PREVIOUS: "以前",
    SUBMIT: "提交",
    FINISH: "完成",
    SKIP: "跳过",
    QUIZ_INSTRUCTIONS: "测验说明",
    QUIZ_RESULT: "测验结果",
    YOUR_SCORE: "您的积分",
    EARNED_TOKENS: "赚取的代币",
    CLOSE: "关闭",
    FISCAL_CODE: "财政代码",
    EDUCATION: "学历",
    CITY: "城市",
    JOB_LEVEL: "工作级别",
    SAVE_PROFILE: "保存简介",
    PROFILE: "简介",
    CHANGE_PASSWORD: "改变密码",
    CHEERS: "加油",
    STREAMS: "气氛",
    FAN_RATING_TV: "FAN RATING TV",
    NEWS: "NEW新闻",
    FILTER_BY: "筛选",
    PRIVACY_POLICY: "隐私政策",
    TERMS_AND_CONDITION: "条款与协议",
    MISSION: "任务",
    HELP: "帮助",
    CONTACT_US: "联系我们",
    RANKING: "排行",
    BUY_PACKAGE: "套餐购买",
    THANK_YOU_FOR_REVIEW: "谢谢您的评论",
    THANK_YOU_FOR_VOTING:
        "谢谢您的提交！您的积分将在比赛结束后24小时内有效。请您耐心等！",
    COUNTRY: "国家",
    WATCH_ON: "观看DAZN",
    GO_TO_SAN_SIRO_STADIUM: "前往圣西罗体育场",
    GIFT_CARD: "礼品卡",
    DISCOUNT_CODES: "折扣代码",
    PRIME_SPECIAL: "会员价格",
    GOALS: "进球数",
    VOTES: "投票数",
    PLAYED_MATCHES: "过去的比赛",
    RANK: "等级",
    DESCRIPTION: "说明",
    NEXT_2: "下一步",
    FORGOT_PASSWORD_CAPITAL: "忘记密码?",
    PASSWORD_CHANGE_SUCCESSFULY: "成功密码更新",
    YOUR_PROFILE: "简介",
    GOAL: "进球",
    AVERAGE_FAN_RATING: "平均评价等级",
    ACCEPT_TERMS_AND_CONDITION: "接受条款和条件",
    CONGRATULATION: "祝贺",
    YOUR_RATE_CARD: "您的评价卡",
    REDEEM_FOR_TOKENS: "兑换代币",
    LIVE: "直播",
    POSTED_ON: "发布时刻",
    MESSAGE: "消息",
    IN_PROGRESS: "进行中",
    CONCLUDED: "他总结道",
    Look_at_all: "所有的",
    Share_review: "与朋友享受",
    Find_out: "查看您英国跟",
    remaining: "剩余的",
    how_to_play: "怎么玩？",
    ABOUT_US: "关于我们",
    MY_TEAM: "我的球队",
    FAN: "足球迷",
    TV_SUBSCRIBER: "电视用户",
    STADIUM_SUBSCRIBER: "现场用户",
    OCCASIONAL: "偶尔的",
    YES_LETS_START_CHEERING: "是的，让我开始欢呼",
    NO_I_WANT_TO_CHANGE: "不，我要换别的",
    PROFESSION: "专家",
    UPLOAD_A_PHOTO: "提交简介",
    SAVE_PHOTO: "保存简介",
    GAMES_PLAYED: "过去的比赛",
    NATIONALITY: "国籍",
    HEIGHT: "身高",
    WEIGHT: "重量",
    I_AM_18_YEARS_OLD: "我是成人的",
    REQUIRED_TO_MAKE_IN_APP_PURCHASES_AND_ACCESS_THE_REWARDS_CATALOG:
        "需要进行应用内购买并访问奖励目录.",
    SELECT_YOUR_HEART_TEAM: "选择您的心脏团队",
    QUIZ_CONGRATULATIONS: `恭喜你，你是测验冠军！所有问题你都答对了！`,
    QUIZ_TRY_AGAIN: `你必须多准备一点，但别担心，你可以弥补下一次测验！`,
    CONGRATULATIONS: "恭喜你!",
    BETTER_LUCK_NEXT_TIME: "下次你会更幸运",
    INVITE_A_FRIEND_AND_RECEIVE_25_TOKENS:
        "邀请朋友并获得25个代币",
    INVITE_FRIENDS_DESCRIPTION:
        "您可以邀请朋友注册Fan Rating，并获得25个代币. 记住, 一旦朋友完成注册通过邀请链接，您将获得代币",
    INVITE_A_FRIEND: "邀请朋友",
    INVITE_AND_REFER: "邀请和推荐",
    BUY_TOKENS: "购买代币",
    TOKENS: "代币",
    MAKE_A_PAYMENT: "付款",
    TRANSACTION_LIST: "交易记录",
    YOUR_TOKENS: "您的代币",
    VOTE_other_matches: "投票其他比赛",
    LIKES: "喜欢",
    SURVEY_INSTRUCTIONS: "调查说明",
    SURVEY: "调查",
    SURVEY_COMPLETED: "非常感谢！您的提交已收到",
    RESET_PASSWORD: "重置密码",
    WARNING: "注意!",
    OOPS: "哎呀！",
    ALERT: "警戒!",
    Something_went_wrong: "出了一些问题！",
    SUCCESS: "成功!",
    ENTER_YOUR_EMAIL: "输入您的邮件地址",
    ENTER_YOUR_PASSWORD: "输入您的密码",
    ENTER_YOUR_FIRST_NAME: "输入您的名字",
    ENTER_VALID_FIRSTNAME: "请输入有效的名字",
    ENTER_YOUR_LAST_NAME: "输入您的姓",
    ENTER_VALID_LASTNAME: "请输入有效的姓",
    ENTER_YOUR_USER_NAME: "输入您的用户名",
    ENTER_VALID_USERNAME: "请输入有效的用户名",
    ENTER_YOUR_DATE_OF_BIRTH: "输入您的生日",
    ENTER_YOUR_GENDER: "输入您的性别",
    PLEASE_ACCEPT_TERMS_AND_CONDITIONS: "请接受条款和条件",
    PLEASE_SELECT_IF_YOU_ARE_18: "请选择如果您已是成年",
    PASSWORD_MUST_BE_BETWEEN_8_AND_12: "密码必须至少包含8个字符",
    BOTH_PASSWORDS_MUST_BE_SAME: "两个密码必须相同",
    PLEASE_ENTER_VALID_EMAIL_ADDRESS: "请输入有效的邮件地址",
    PLEASE_ENTER_VALID_BIRTHDATE: "请输入有效的生日",
    SELECT_YOUR_GENDER: "选择您的性别",
    SELECT_YOUR_JOB_LEVEL: "选择您的工作级别",
    SELECT_YOUR_EDUCATION: "选择您的学历",
    SELECT_AN_OPTION: "选择一个选项",
    SELECT_YOUR_CITY: "选择您的城市",
    SELECT_YOUR_COUNTRY: "选择您的国籍",
    No_cards: "没有可用的信用卡!",
    Use_default_card: "将此卡用作默认卡",
    CARD_LIST: "信用卡目录",
    ADD_CARD: "添加",
    Add_New_Card: "添加新的信用卡",
    Pay: "支付",
    Card_Details: "信用卡的详细信息",
    ACCEPT_TC: "接受条款和条件",
    Delete_Message: "确实要删除此信用卡吗？",
    Logout_Message: "你确定要注销吗？",
    SORRY_NO_DATA_FOUND: "对不起，没有找到数据!",
    NAME: "姓名",
    REMOVE_ALL_NOTIFICATION: "是否确实要删除所有通知？",
    Average_Vote: "平均投票数",
    PLAYER_NAME: "队员姓名",
    Players: "队员们",
    Substitute: "代替",
    Coach: "教练",
    TO_UNLOCK_MATCH: "解锁比赛",
    BUY_MATCH_BTN_TEXT: "解锁",
    TOKENS_VALUE: "代币",
    SHARE_BTN: "分享",
    UNLOCK_MATCH:
        "如果你想让更多的比赛进行投票，你应该通过从比赛中获得更多的分数来提高你的水平",
    INVITE_INFO:
        "您好，我想邀请您加入FR-PWA申请，请点击下面的链接并注册您的帐户.",
    LEVEL: "等级",
    HURRY_UP_VOTE: "快点投票很快就要结束了！",
    MATCH_RESULTS:
        "比赛结束后24小时后将显示结果！",
    QUIZ: "测验",
    SELECT_TEAM: "选择球队",
    SELECT_YOUR_TEAM: "选择您的球队",
    CHANGE_TEAM: "变更球队",
    CHOOSE_YOUR_TEAM: "选择您的球队",
    INDEX: "目录",
    VOTE_FOR_MATCHES: "为比赛投票",
    SOMETHING_WENT_WRONG: "出了一些问题",
    REMOVE_ALL: "全部删除",
    VERIFICATION_SUCCESS: "您的帐户已成功验证",
    VERIFICATION_FAILED: "您的帐户已被拒绝.",
    GO: "进行",
    EMAIL_VERIFICATION: "电子邮件验证",
    WELCOME: "欢迎",
    toFanSerie: "达到A级Fan Rating!",
    KICK_OFF: "开球时间所剩无几",
    WHY_WAIT: "但为什么要等待？",
    CANCEL: "取消",
    OK: "确认",
    UPCOMING_MATCH: "即将到来的比赛！",
    VOTE_ENABLED: "比赛结束后将启用投票.",
    Password_Success: "密码更改成功!",
    VOTING_CONFIRMATION:
        "您想确认您对{{TEAMA}}和{{TEAMB}}的评评价吗？确认后，您不能更改评价.",
    WINNERS: "查看足球迷冠军",
    VERIFIED: "您已验证!",
    NOT_VERIFIED: "您未经验证!",
    FAQ: "查阅常见问题解答",
    HOW_TO_PLAY: "了解如何玩",
    BECOME_TESTER: "立即成为体验人员",
    SORRY_THIS_PAGE_IS_NOT_AVAILABLE: "抱歉，此页面不可用.",
    THE_LINK_YOU_FOLLOWED_MAY_BE_BROKEN:
        "您所关注的链接可能已断开，或者页面已被删除.",
    GO_BACK_TO_FANRATINGWEB: "返回向FanRatingWeb",
    CONFIRM_REDEEM:
        "你确定要兑换{{productName}}吗? 代码将发送到您在注册期间使用的电子邮件",
    GOALKEEPER: "门将",
    DEFENDER: "守卫",
    MIDFIELDER: "前卫",
    FORWARD: "前方",
    COACH: "教练",
    SIGNUP_EMAIL: "使用电子邮件注册",
    INVITE_AND_EARN: "邀请 & 获得",
    ADD_COMMENT: "添加评论 . . .",
    UNLOCK: "解锁",
    PASSWORD_MUST_BE_MINIMUM_OF_8_CHARACTERS:
        "密码必须至少包含8个字符",
    CHOOSE_FILE: "选择文件",
    EIGHTEEN_PLUS: "您必须年满18岁才能继续!",
    FIRSTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "名字应至少包含3个字母",
    LASTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "姓应至少包含3个字母",
    USERNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "用户名应至少包含3个字母",
    Be_First_to_like: "成为第一个喜欢的人",
    PROFILE_UPDATED: "简介图片更新了.",
    APPLE_WARN:
        "您想使用旧的Apple帐户登录吗？然后重置密码.",
    BUY_MORE_TOKENS: "购买更多代币",
    SELECT_ONE_OPTION: "请选择任意一个选项!",
    VALID_DATE: "请输入有效日期",
    NOT_LEAP_YEAR: "输入的日期不是闰年",
    INVLAID_LEAP_YEAR: "无效的闰年日期",
    INVALID_MONTH: "无效月份",
    INVALID_YEAR: "无效年份",
    FUTURE_DATE: "您不能输入未来日期",
    ALTEAST_EIGHTEEN: "您必须年满13岁",
    AWARD_REDEEMED: "奖励兑现!",
    CONGRATULATIONS_YOU_JUST_EARNED_A_COIN:
        "祝贺!你刚刚赚了一枚硬币!",
    OFFLINE_TITLE: "您处于未连线的模式",
    OFFLINE_SUB_TITLE: "你的应用处于未连线的模式.",
    OFFLINE_DESC: "检查您的互联网连接或wi-fi设置",
    OFFLINE_REFRESH_BTN: "刷新",
    MATCH: "比赛",
    POSITION: "位置",
    FAN_WINNERS: "足球迷冠军",
    VOTE_NEW: "投票",
    DEVICE_INFO1: "不知道如何在设备上安装Fan Rating?",
    DESCTOP_INFO1: "不知道如何在设备上安装Fan Rating?",
    DEVICE_INFO2: "点击下面了解如何操作",
    DESCTOP_INFO2: "点击下面了解如何操作",
    DESCTOP_BTN_NAME: "点击这里",
    DEVICE_BTN_NAME: "点击此处",
    NEW_MENU_OPTION: "安装风扇评级",
    EARNED_MORE_TOKENS:
        "你没有足够的Fan币来获得这个奖项。赚取更多或购买",
    TEASING_ROOM: "茶室",
    TEASING_ROOM_TITLE: "茶馆的角落",
    CAPTION: "标题",
    MEDIA: "媒体",
    ADD_POST: "添加评价",
    READY_TO_SEND: "准备好发送了吗?",
    DELETE_POST: "是否确实要删除评价?",
    MY_POST: "我的评价",
    POST_CAPTION: "输入标题...",
    REPORT_POST: "公布评价",
    REPORT_REASON: "理由",
    REASON_PLACEHOLDER: "添加报告的理由...",
    INCREASE_LEVEL: "提高你的级别",
    CHECK_EMAIL:
        "感谢您兑换此奖励，请检查收件箱中的代码.",
    ADD_POST_VALIDATION: "请添加图像或视频",
    ADD_CAPTION_VALIDATION: "添加标题",
    NO_COMMENT: "目前没有可用的评论.第一个发表评论.",
    LEVEL_PRICE: "级别价格",
    INCREASE_LEVEL1: "升级级别",
    ENTER_REPORT: "请输入理由",
    EDIT_POST: "编辑文章",
    UPLOAD_FAILED: "无法上载mkv文件。请选择mp4/webm",
    COMMENT_SCREEN_TITLE: "评论",
    MOST_COMMENTS: "大多数评论",
    MOST_LIKES: "最喜欢的",
    MOST_RECENT: "最新动态",
    ORDER_BY: "排序依据",
    TEAM_TAG: "足球对标记",
    SELECT_TEAM_TAG: "选择足球队标记",
    FIRST_POST: "这里真是一片寂静,用你的第一篇文章让其他足球迷开怀大笑",
    INVALID_FILE: "文件类型无效",
    UPLOAD_DOCUMENT: "上载文档",
    SAVE_DOCUMENT: "保存文档",
    PLEASE_SELECT_FILE: "请选择文件",
    New_Token_key: "使用代币",
    showMore: "显示更多信息",
    reply: "回复",
    ALL_VIDEOS: "所有视频",
    ALL_NEWS: "所有信息",
    LIKE: "喜欢",
    ATTENTION: "注意!",
    VOTE_ALL_PLAYERS: "请投票给所有队员",
    WELCOME_BACK_ONBOARD: "欢迎回到!",
    SIGN_IN_WITH_EAMIL: "使用电子邮件登录",
    WELCOME_TO_FAN_RATING: "欢迎到Fan Rating",
    BACK: "返回",
    NOT_REGISTERED_YET: "未经注册吗? ",
    CREATE_AN_ACCOUNT: "创新用户",
    JOIN_THE_COMMUNITY_OF_FOOTBALL_FANS: "加入足球迷社区!",
    CONFIRM: "确认",
    CONTINUE_VOTE: "确认你的投票",
    NOTE_TWO_TEAMS: "您有 2 个团队可以投票",
    INSTALL_APP_ON_IPHONE: "在 iPhone 上安装",
    INSTALL_APP_ON_ANDROID: "安装在安卓上",

    FAN_COINGS_LEVET_UP_CONFIRM_MESSAGE: "您需要 {level_price} FanCoins 来升级。 你确定你要继续吗？",
    FAN_SUBSCRIBER_TV: "订户电视",
    FAN_SEASON_TICKET: "订户体育场",
    FAN_OCCA: "偶尔",
    PROFILE_UPDATE_MESSAGE: "您的个人资料已更改",
    Phone: "電話",
    ENTER_YOUR_PHONE: "輸入您的電話.",
    // new words 3/10/2023
    FUN_VERSE: 'FunVerse',
    REGISTER: '登记'
};
