export const EnLanguage = {
  TEAMLIST_TITLE: "SELECT YOUR\nTEAM",
  NOTIFICATION: "Notification",
  TEAMLIST_DESC:
    "Remember that you can no longer change it, it will be the only team you vote for",
  TEAMLIST_DESC2: "for free and from you will receive news",
  NEXT: "Next",
  NEXT_2: "Next",
  TIFA: "Cheer",
  RATE_IT: "Rate",
  WIN: "Win",
  ALL: "All",
  CURRENT: "Current",
  PAST: "Your rate cards",
  RATE: "Vote",
  VOTE: "Vote",
  VIEW: "Watch",
  ACHIEVEMENTS: "Win",
  PRIME_AMAZON: "Amazon Prize",
  PARTNERS_PRIZES: "Partners’ Prizes",
  LIMITED_AVAILABILITY: " LIMITED AVAILABILITY ",
  VIEW_ALL: "View All",
  FORGOT_PASSWORD_CAPITAL: " FORGOT PASSWORD?",
  FORGOT_PASSWORD: "PASSWORD DIMENTICATA",
  Forgot_Password: "Password dimenticata?",
  NEW_PASSWORD: "New Password",
  CONFIRM_NEW_PASSWORD: "Confirm New Password",
  SAVE_PASSWORD: "Save Password",
  LOGIN: "LOGIN",
  EDIT_PROFILE: "EDIT PROFILE",
  SIGN_OUT: "SIGN OUT",
  SIGN_IN: "SIGN IN",
  SIGN_IN_CAPITAL: "SIGN IN",
  SIGN_UP: " SIGN UP",
  YOUR_TOKENS: "YOUR FANCOINS",
  SIGN_UP_CAPITAL: " SIGN UP",
  TOKEN: "FanCoins",
  POINTS: "Points",
  EMAIL: "E-mail",
  PASSWORD: `Password`,
  OR: "OR",
  SIGN_IN_WITH_APPLE: "Sing in with Apple",
  SIGN_IN_WITH_FACEBOOK: "Sing in with Facebook",
  SIGN_IN_WITH_GOOGLE: "Sing in with Google",
  SIGN_UP_WITH_APPLE: "Sign in with Apple",
  // SIGN_Up_WITH_FACEBOOK: "Sign in with Facebook",
  // SIGN_Up_WITH_GOOGLE: "Sign in Google",
  NO_ACCOUNT: "No account?",
  HAVE_ACCOUNT: `Have an account?`,
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  GENDER: "Gender",
  DATE_OF_BIRTH: "Date of Birth",
  USERNAME: "Username",
  CREATE_ACCOUNT: "Create Account",
  SIGN_UP_WITH_FACEBOOK: "Sign up with Facebook",
  SIGN_UP_WITH_GOOGLE: " Sign up with Google",
  MALE: "Male",
  FEMALE: "Female",
  OTHER: "Other",
  THANK_YOU_FOR_SUBMITTING: ` THANK YOU FOR SUBMITTING `,
  PASSWORD_CHANGE_SUCCESSFULY: "PASSWORD CHANGE SUCCESSFULY",
  PASSWORD_CHANGE_SUCCESSFUL: "PASSWORD CHANGE SUCCESSFULY",
  PREVIOUS: "Previous",
  SUBMIT: "Submit",
  FINISH: "Watch Result",
  SKIP: "Skip",
  QUIZ_INSTRUCTIONS: "QUIZ INSTRUCTIONS",
  QUIZ_RESULT: "QUIZ RESULT",
  YOUR_SCORE: "YOUR SCORE",
  EARNED_TOKENS: "FANCOINS EARNED",
  CLOSE: "Close",
  FISCAL_CODE: "NIF",
  EDUCATION: "Education",
  CITY: "City",
  PROFESSION: "Job",
  SAVE_PROFILE: "Save profile",
  YOUR_PROFILE: "Your profile",
  CHANGE_PASSWORD: "CHANGE PASSWORD",
  CHEERS: "CHEERS",
  STREAMS: "STREAMING",
  FAN_RATING_TV: "FAN RATING TV",
  NEWS: "BLOG",
  FILTER_BY: "Filter by",
  PRIVACY_POLICY: "Privacy Policy",
  TERMS_AND_CONDITION: "Terms and Conditions",
  MISSION: "Mission",
  HELP: "Rules and FAQ",
  CONTACT_US: "Contact us",
  RANKING: "Ranking",
  BUY_PACKAGE: "Buy package",
  THANK_YOU_FOR_REVIEW: "THANK YOU FOR REVIEW",
  THANK_YOU_FOR_VOTING: "THANK YOU FOR VOTING. Your points will be available within 24h",
  COUNTRY: "Country",
  WATCH_ON: "Watch on TV",
  GO_TO_SAN_SIRO_STADIUM: "Buy Tickets",
  GIFT_CARD: "Gift Card",
  DISCOUNT_CODES: "Discount Codes",
  PRIME_SPECIAL: "Special Prizes",
  GOAL: "Goal!",
  AVERAGE_FAN_RATING: "FanRate",
  PLAYED_MATCHES: "Played Matches",
  RANK: "Ranking",
  DESCRIPTION: "Description",
  ACCEPT_TERMS_AND_CONDITION: "Accept Terms and Conditions",
  CONGRATULATION: "Congratulation",
  YOUR_RATE_CARD: "Your Rate Card",
  REDEEM_FOR_TOKENS: "Redeem your FanCoins",
  LIVE: "LIVE",
  POSTED_ON: "Posted on",
  MESSAGE: "Message",
  IN_PROGRESS: "In Progress",
  CONCLUDED: "Your rate cards",
  ABOUT_US: "About us",
  MY_TEAM: "My Team",
  FAN: "Fan",
  TV_SUBSCRIBER: "TV Subscriber",
  STADIUM_SUBSCRIBER: "Stadium Subscriber",
  OCCASIONAL: "Occasional",
  JOB_LEVEL: "Job",
  YES_LETS_START_CHEERING: "Yeah! Let’s start!",
  NO_I_WANT_TO_CHANGE: "No, I want to change",
  Look_at_all: "Look at all",
  Share_review: "Share rate card",
  Find_out: "Find out if you won",
  remaining: "remaining",
  how_to_play: "How to play?",
  UPLOAD_A_PHOTO: "UPLOAD A PHOTO",
  SAVE_PHOTO: "SAVE PHOTO",
  GAMES_PLAYED: "Matches played",
  NATIONALITY: "Nationality",
  HEIGHT: "Height",
  WEIGHT: "Weight",
  I_AM_18_YEARS_OLD: "I’m 13 years old",
  REQUIRED_TO_MAKE_IN_APP_PURCHASES_AND_ACCESS_THE_REWARDS_CATALOG:
    " REQUIRED TO MAKE IN-APP_PURCHASES AND ACCESS THE_FAN CATALOG ",
  SELECT_YOUR_HEART_TEAM: "SELECT YOUR FAVORITE TEAM",
  QUIZ_CONGRATULATIONS: `Congratulations! You are the Quiz Winner!`,
  QUIZ_TRY_AGAIN:
    "Don’t worry, try again next quiz and you will be luckier!",
  CONGRATULATIONS: "Congratulations!",
  BETTER_LUCK_NEXT_TIME: "You'll be luckier next time",
  INVITE_A_FRIEND_AND_RECEIVE_25_TOKENS:
    "Invite a friends and you receive 25 FanCoins",
  INVITE_FRIENDS_DESCRIPTION:
    "You can invite friends to register in Fan Rating and you will receive 25 FanCoins! Puoi invitare un amico a registrarsi su Fan Rating e ricevere 25 Fan Coins, once he will be registered through the inviation link",
  INVITE_A_FRIEND: "Invite a friend",
  INVITE_AND_REFER: "Invite a friend",
  BUY_TOKENS: "Buy FanCoins",
  TOKENS: "FanCoins",
  MAKE_A_PAYMENT: "Make a payment",
  TRANSACTION_LIST: "Transaction list ",
  VOTE_other_matches: "VOTE other matches",
  LIKES: "Likes",
  SURVEY_INSTRUCTIONS: "SURVEY INSTRUCTIONS",
  SURVEY: "SURVEY",
  SURVEY_COMPLETED: "THANK YOU! YOUR OPINION I REGISTERED",
  RESET_PASSWORD: "Reset password",
  WARNING: "WARNING!",
  OOPS: "OOPS!",
  ALERT: "ALLERT",
  Something_went_wrong: " Something went wrong",
  SUCCESS: "Success!",
  ENTER_YOUR_EMAIL: "Enter your email",
  ENTER_YOUR_PASSWORD: "Enter your password",
  ENTER_YOUR_FIRST_NAME: "Enter your first name",
  ENTER_VALID_FIRSTNAME: "Enter your valid first name",
  ENTER_YOUR_LAST_NAME: "Enter your last name",
  ENTER_VALID_LASTNAME: "Enter your valid last name ",
  ENTER_YOUR_USER_NAME: "Enter your username ",
  ENTER_VALID_USERNAME: "Enter your valid username ",
  ENTER_YOUR_DATE_OF_BIRTH: "Enter your date of birth",
  ENTER_YOUR_GENDER: "Enter your gender",
  PLEASE_ACCEPT_TERMS_AND_CONDITIONS:
    "Please accept Terms & Conditions",
  PLEASE_SELECT_IF_YOU_ARE_18: "Please select if you are 18 or more years old",
  PASSWORD_MUST_BE_BETWEEN_8_AND_12:
    "Password must have between 8 to 12 characters",
  BOTH_PASSWORDS_MUST_BE_SAME: "Both passwords must be the same",
  PLEASE_ENTER_VALID_EMAIL_ADDRESS: "Please enter a valid email address",
  PLEASE_ENTER_VALID_BIRTHDATE: "Please enter a valid birthdate",
  SELECT_YOUR_GENDER: "Select your gender",
  SELECT_YOUR_JOB_LEVEL: "Select your Job",
  SELECT_YOUR_EDUCATION: "Select your education",
  SELECT_AN_OPTION: "Select an option",
  SELECT_YOUR_CITY: "Select your City",
  SELECT_YOUR_COUNTRY: "Select your Country",
  No_cards: "No cards",
  Use_default_card: "Use_default_card",
  CARD_LIST: "CARD LIST",
  ADD_CARD: "ADD CARD",
  Add_New_Card: "Add new card",
  Pay: "Pay",
  Card_Details: "Card Details",
  ACCEPT_TC: "Accept Terms & Conditions",
  Delete_Message: "Are you sure you want to delete this card?",
  Logout_Message: "Are you sure you want to log out?",
  SORRY_NO_DATA_FOUND: "Sorry, no data found!",
  NAME: "Name",
  REMOVE_ALL_NOTIFICATION: "Are you sure you want to delete all the notifications?",
  Average_Vote: "FanRate",
  PLAYER_NAME: "Player Name",
  Players: "Players",
  Substitute: "Substitute",
  Coach: "Coach",
  TO_UNLOCK_MATCH: "TO UNLOCK THE MATCH",
  BUY_MATCH_BTN_TEXT: "UNLOCK",
  TOKENS_VALUE: "FanCoins",
  SHARE_BTN: "SHARE",
  UNLOCK_MATCH: "Want to rate more games? Level up by earning points!",
  INVITE_INFO:
    " Hi! I would like to invite you to Fan Rating, please click the link and register your account",
  LEVEL: "Level",
  HURRY_UP_VOTE: "Hurry up! Voting will close soon!",
  MATCH_RESULTS:
    "Results will be displayed 24 hours after the end of the match!",
  QUIZ: "QUIZ",
  SELECT_TEAM: "Select Team",
  SELECT_YOUR_TEAM: "Select your Team",
  CHANGE_TEAM: "Change Team",
  CHOOSE_YOUR_TEAM: "Choose your team",
  INDEX: "INDEX",
  VOTE_FOR_MATCHES: "MATCHES TO VOTE",
  SOMETHING_WENT_WRONG: "Something went wrong",
  REMOVE_ALL: "Remove all",
  VERIFICATION_SUCCESS: "Your account has been successfully verified",
  VERIFICATION_FAILED: "Your account has been refused",
  GO: "GO!",
  EMAIL_VERIFICATION: "Email verification",
  WELCOME: "Welcome",
  toFanSerie: "to Fan Rating!",
  KICK_OFF: "It's almost kick-off",
  WHY_WAIT: "Why waiting?",
  CANCEL: "Cancel",
  OK: "Ok",
  UPCOMING_MATCH: "UPCOMING MATCH!",
  VOTE_ENABLED: "You will be able to vote at the end of the match!",
  Password_Success: "Password change successfully!",
  VOTING_CONFIRMATION:
    "Confirm your rate card for {{TEAMA}} and {{TEAMB}}? You will not be able to modify once you confirm.",
  WINNERS: "FAN WINNER",
  VERIFIED: "VERIFIED!",
  NOT_VERIFIED: "NOT VERIFIED!",
  FAQ: "FAQ",
  HOW_TO_PLAY: "HOW TO PLAY",
  BECOME_TESTER: "Become a tester",
  SORRY_THIS_PAGE_IS_NOT_AVAILABLE:
    "SORRY THIS PAGE IS NOT AVAILABLE.",
  THE_LINK_YOU_FOLLOWED_MAY_BE_BROKEN:
    "The link you followed may be broken or the page may have been removed.",
  GO_BACK_TO_FANRATINGWEB: "Go back to FanRatingWeb",
  CONFIRM_REDEEM:
    "Are you sure to redeem your {{productName}}? The redeem code will be sent to your registered email",
  GOALKEEPER: "Golkeeper",
  DEFENDER: "Defender",
  MIDFIELDER: "Midfielder",
  FORWARD: "Forward",
  COACH: "Coach",
  SIGNUP_EMAIL: "Sign up with your e-mail",
  INVITE_AND_EARN: "Invite friends and earn",
  ADD_COMMENT: "Add a comment . . .",
  UNLOCK: "UNLOCK",
  PASSWORD_MUST_BE_MINIMUM_OF_8_CHARACTERS:
    "The password must be minimum 8 characters",
  CHOOSE_FILE: "Choose a file",
  EIGHTEEN_PLUS: "You must be 18 years old or more to proceed!",
  FIRSTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
    "First name should be at least 3 letters",
  LASTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
    "last name should be at least 3 letters",
  USERNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
    "Username should be at least 3 letters",
  Be_First_to_like: "Be the first to like!",
  PROFILE_UPDATED: "Immage updated",
  APPLE_WARN:
    "Are you already registered with an Apple account? To access, request a new password.",
  BUY_MORE_TOKENS: "Buy more FanCoins",
  SELECT_ONE_OPTION: "Select one option!",
  VALID_DATE: "Please enter a valid date",
  NOT_LEAP_YEAR: "The date entered is not a leap year",
  INVLAID_LEAP_YEAR: "The data entered is not a leap year",
  INVALID_MONTH: "Invalid month",
  INVALID_YEAR: "Invalid year",
  FUTURE_DATE: "Invalid date",
  ALTEAST_EIGHTEEN: "You have to be at least 13 years old",
  AWARD_REDEEMED: "AWARD REDEEMED!",
  CONGRATULATIONS_YOU_JUST_EARNED_A_COIN:
    "Congratulations! You just earned a FanCoin!",
  OFFLINE_TITLE: "You are offline",
  OFFLINE_SUB_TITLE: "Your app is offline",
  OFFLINE_DESC:
    "Check your internet connexion or your Wi-Fi settings.",
  OFFLINE_REFRESH_BTN: "Refresh",
  MATCH: "Match",
  POSITION: "Position",
  FAN_WINNERS: "Fan Winners",
  VOTE_NEW: "Rate",
  DEVICE_INFO1: "Do you know how to install Fan Rating on your device?",
  DESCTOP_INFO1: "Do you know how to install Fan Rating on your device?",
  DEVICE_INFO2: "Find out how to do it, click below",
  DESCTOP_INFO2: "Find out how to do it, click below",
  DESCTOP_BTN_NAME: "Click here",
  DEVICE_BTN_NAME: "Touch here",
  NEW_MENU_OPTION: "Install Fan Rating",
  EARNED_MORE_TOKENS:
    "You don't have enough FanCoins for this prize. Play and earn more or buy them",
  TEASING_ROOM: "Teasing community",
  TEASING_ROOM_TITLE: "Teasing corner",
  CAPTION: "Caption",
  MEDIA: "Media",
  ADD_POST: "Tease!",
  READY_TO_SEND: "READY TO SEND?",
  DELETE_POST: "Sure to delete this post?",
  MY_POST: "My teases",
  POST_CAPTION: "Enter the caption here ...",
  REPORT_POST: "Report post",
  REPORT_REASON: "Reason report",
  REASON_PLACEHOLDER: "Add your reason of the report ....",
  INCREASE_LEVEL: "Increase your level!",
  CHECK_EMAIL:
    "Thank you for redeeming this reward, check your inbox for your code.",
  ADD_POST_VALIDATION: "Add images or videos",
  ADD_CAPTION_VALIDATION: "Add caption",
  NO_COMMENT:
    "There are no comments available at this time. Be the first to leave a comment.",
  LEVEL_PRICE: "LEVEL COINS",
  INCREASE_LEVEL1: "LEVEL UP",
  ENTER_REPORT: "Motivation of the report",
  EDIT_POST: "Edit post",
  UPLOAD_FAILED: "Upload failed of files in mkv. Select mp4/webm",
  COMMENT_SCREEN_TITLE: "Comments",
  MOST_COMMENTS: "Most commented",
  MOST_LIKES: "Most likes",
  MOST_RECENT: "Most recent",
  ORDER_BY: "Order by",
  TEAM_TAG: "Team Tag",
  SELECT_TEAM_TAG: "Select team tag",
  FIRST_POST:
    "What a silence here, make other Fans laugh with your first tease",
  INVALID_FILE: "Invalid file",
  UPLOAD_DOCUMENT: "UPLOAD DOCUMENT",
  SAVE_DOCUMENT: "Save document",
  PLEASE_SELECT_FILE: "Please select file",
  New_Token_key: "Level Up",
  showMore: "Show more",
  reply: "Reply",
  ALL_VIDEOS: "All the videos",
  ALL_NEWS: "All the news",
  LIKE: "Like",
  ATTENTION: "ATTENTION!",
  VOTE_ALL_PLAYERS: "Vote all the players! ",
  WELCOME_BACK_ONBOARD: "Welcome back onboard!",
  SIGN_IN_WITH_EAMIL: "Sign with email",
  WELCOME_TO_FAN_RATING: "Welcome to Fan Rating",
  BACK: "Back",
  NOT_REGISTERED_YET: "Not registered yet? ",
  CREATE_AN_ACCOUNT: "Create an Account!",
  JOIN_THE_COMMUNITY_OF_FOOTBALL_FANS: "Join our community of football fans where you are the real protagonist!",

  CONFIRM: "Confirm",
  CONTINUE_VOTE: "Confirm a Vote",
  NOTE_TWO_TEAMS: "You have two teams and two report cards to vote on",
  INSTALL_APP_ON_IPHONE: "Install On Iphone",
  INSTALL_APP_ON_ANDROID: "Install On Android",

  FAN_COINGS_LEVET_UP_CONFIRM_MESSAGE: "You need {level_price} Fan Coins to level up, are you sure you want to proceed?",
  FAN_SUBSCRIBER_TV: "Subscriber TV",
  FAN_SEASON_TICKET: "Stadium season ticket holder",
  FAN_OCCA: "Occasional",
  PROFILE_UPDATE_MESSAGE: "Your profile has been updated.",
  // new words 1/4/23
  Phone: "Mobile Phone",
  ENTER_YOUR_PHONE: "Enter your moblie phone.",
  SELECT_LEAGUE: "Select League.",
  LEAGUE: "League",
  // new words 3/10/2023
  FUN_VERSE: 'FunVerse',
  REGISTER: 'REGISTER'
}