export const FrLanguage = {
    TEAMLIST_TITLE: "Sélectionne ton\équipe",
    NOTIFICATION: "Notification",
    TEAMLIST_DESC:
        "Souviens-toi que tu ne pourras plus le changer, ce sera la première équipe pour laquelle tu voteras",
    TEAMLIST_DESC2: "gratuit et dont tu recevras des nouvelles",
    NEXT: "Suivant",
    NEXT_2: "Suivant",
    TIFA: "SOUTIENS",
    RATE_IT: "VOTE",
    WIN: "GAGNE",
    ALL: "Tous",
    CURRENT: "En cours",
    PAST: "Mes notes ",
    RATE: "VOTE",
    VOTE: "Vote",
    VIEW: "Regarde",
    ACHIEVEMENTS: "GAGNE",
    PRIME_AMAZON: "PRIX AMAZON",
    PARTNERS_PRIZES: "PRIX DES PARTNAIRES",
    LIMITED_AVAILABILITY: "DISPONIBILITÉ LIMITÉE",
    VIEW_ALL: "Regarder tous",
    FORGOT_PASSWORD_CAPITAL: "MOT DE PASSE OUBLIÉ?",
    FORGOT_PASSWORD: "Mot de passe oublié",
    Forgot_Password: "Mot de passe oublié",
    NEW_PASSWORD: "Nouveau mot de passe",
    CONFIRM_NEW_PASSWORD: "Confirmer nouveau mot de passe",
    SAVE_PASSWORD: "Sauvegarder mot de passe",
    LOGIN: "Se connecter",
    EDIT_PROFILE: "Modifier profil",
    SIGN_OUT: "Se déconnecter",
    SIGN_IN: "Accéder",
    SIGN_IN_CAPITAL: "ACCEDER",
    SIGN_UP: "S’enregistrer",
    YOUR_TOKENS: "Mes FanCoins",
    SIGN_UP_CAPITAL: "S’ENREGISTRER",
    TOKEN: "FanCoins",
    POINTS: "Points",
    EMAIL: "E-mail",
    PASSWORD: "Mot de passe",
    OR: "Ou",
    SIGN_IN_WITH_APPLE: "Accéder avec Apple",
    SIGN_IN_WITH_FACEBOOK: "Accéder avec Facebook",
    SIGN_IN_WITH_GOOGLE: "Accéder avec Google",
    SIGN_UP_WITH_APPLE: "S’enregistrer avec Apple",
    // SIGN_Up_WITH_FACEBOOK: "S’enregistrer avec Facebook",
    // SIGN_Up_WITH_GOOGLE: "S’enregistrer avec Google",
    NO_ACCOUNT: "Pas de compte?",
    HAVE_ACCOUNT: "As-tu un compte?",
    FIRST_NAME: "Prénom",
    LAST_NAME: "Nom",
    GENDER: "Sexe",
    DATE_OF_BIRTH: "Date de naissance",
    USERNAME: "Nome utilisateur",
    CREATE_ACCOUNT: "Créer un compte",
    SIGN_UP_WITH_FACEBOOK: "S’inscrire avec Facebook",
    SIGN_UP_WITH_GOOGLE: "S’inscrire avec Google",
    MALE: "Homme",
    FEMALE: "Femme",
    OTHER: "R.A.S.",
    THANK_YOU_FOR_SUBMITTING: "Merci",
    PASSWORD_CHANGE_SUCCESSFULY: "MOT DE PASSE MODIFIÉ AVEC SUCCÈS",
    PASSWORD_CHANGE_SUCCESSFUL: "MOT DE PASSE MODIFIÉ AVEC SUCCÈS",
    PREVIOUS: "Précédent",
    SUBMIT: " Envoyer",
    FINISH: "Regarde le résultat",
    SKIP: "Sauter",
    QUIZ_INSTRUCTIONS: "INSTRUCTIONS AU QUIZ",
    QUIZ_RESULT: "MON RÉSULTAT",
    YOUR_SCORE: "MON SCORE",
    EARNED_TOKENS: "FANCOINS GAGNÉS ",
    CLOSE: "Fermer",
    FISCAL_CODE: "NIF",
    EDUCATION: "Formation scolaire",
    CITY: "Ville",
    PROFESSION: "Profession",
    SAVE_PROFILE: "Sauvegarder profil",
    YOUR_PROFILE: "Ton Profil",
    CHANGE_PASSWORD: "CHANGES MOT DE PASSE",
    CHEERS: "Supporte",
    STREAMS: "LIVE",
    FAN_RATING_TV: "FAN RATING LIVE",
    NEWS: "BLOG",
    FILTER_BY: "Filtre par",
    PRIVACY_POLICY: "Privacy Policy",
    TERMS_AND_CONDITION: "Termes et conditions",
    MISSION: "Mission",
    HELP: "Réglement et FAQ",
    CONTACT_US: "Nous contacter",
    RANKING: "Classement",
    BUY_PACKAGE: "Achète des promos",
    THANK_YOU_FOR_REVIEW: "MERCI POUR L’ENVOI",
    THANK_YOU_FOR_VOTING:
        "Merci! Ton score sera disponible 24 heures après la fin du jeu. Reviens vite!",
    COUNTRY: "Pays",
    WATCH_ON: "TV",
    GO_TO_SAN_SIRO_STADIUM: "Billets Stade",
    GIFT_CARD: "Carte cadeau",
    DISCOUNT_CODES: "Code promo",
    PRIME_SPECIAL: "Prix spéciaux",
    GOAL: "But",
    AVERAGE_FAN_RATING: "FanRate",
    PLAYED_MATCHES: "Matches joués",
    RANK: "Classement",
    DESCRIPTION: "Description",
    ACCEPT_TERMS_AND_CONDITION: "J’accepte les Termes et conditions ",
    CONGRATULATION: "Congratulations",
    YOUR_RATE_CARD: "Regarde tes notes",
    REDEEM_FOR_TOKENS: "Rachète avec tes FanCoins",
    LIVE: "LIVE",
    POSTED_ON: "Posté le",
    MESSAGE: "Message",
    IN_PROGRESS: "En cours",
    CONCLUDED: "Mes Bulletins",
    ABOUT_US: "About us",
    MY_TEAM: "Mon équipe",
    FAN: "Fan",
    TV_SUBSCRIBER: "Abonné TV",
    STADIUM_SUBSCRIBER: "Abonné Stade",
    OCCASIONAL: "Occasionnel",
    JOB_LEVEL: "Profession",
    YES_LETS_START_CHEERING: "Oui !Allez-les bleus!",
    NO_I_WANT_TO_CHANGE: "Non, Je veux changer",
    Look_at_all: "Tout regarder",
    Share_review: "Partage tes notes avec tes amis",
    Find_out: "Découvre si tu as gagné",
    remaining: "restant",
    how_to_play: "Comment on joue?",
    UPLOAD_A_PHOTO: "Télécharger une photo",
    SAVE_PHOTO: "Sauvegarder une photo",
    GAMES_PLAYED: "Matches joués",
    NATIONALITY: "Nationalité",
    HEIGHT: "Hauteur",
    WEIGHT: "Poids",
    I_AM_18_YEARS_OLD: "J’ai 13 ans",
    REQUIRED_TO_MAKE_IN_APP_PURCHASES_AND_ACCESS_THE_REWARDS_CATALOG:
        "Requis pour effectuer des achats et accéder au catalogue des fans",
    SELECT_YOUR_HEART_TEAM: "Sélectionne ton équipe",
    QUIZ_CONGRATULATIONS: "Félicitations, tu es le gagnant du quiz ! Tu as répondu correctement à toutes les questions !",
    QUIZ_TRY_AGAIN:
        "Presque ! Prépares-toi un peu plus, mais ne t'inquiète pas, tu pourras te rattraper au prochain quiz !",
    CONGRATULATIONS: "Félicitations!",
    BETTER_LUCK_NEXT_TIME: "La prochaine fois tu auras plus de chance", INVITE_A_FRIEND_AND_RECEIVE_25_TOKENS:
        "Invite un amis et reçois 25 FanCoins",
    INVITE_FRIENDS_DESCRIPTION:
        "Invite un ami à s'inscrire sur Fan Rating et reçois 25 FanCoins. Tu recevras des FanCoins une fois que l'utilisateur aura terminé l'inscription via le lien d'invitation.",
    INVITE_A_FRIEND: "Invite un amis",
    INVITE_AND_REFER: "Invite un amis",
    BUY_TOKENS: "Achète des FanCoins",
    TOKENS: "FanCoins",
    MAKE_A_PAYMENT: "Fait un paiement",
    TRANSACTION_LIST: "Liste des transactions",
    VOTE_other_matches: "VOTE les autres matches",
    LIKES: "Like",
    SURVEY_INSTRUCTIONS: "INSTRUCTIONS POUR LE SONDAGE",
    SURVEY: "SONDAGE",
    SURVEY_COMPLETED: "Merci pour ton opinion!",
    RESET_PASSWORD: "Réinitialiser le mot de passe",
    WARNING: "Attention!",
    OOPS: "Oops!",
    ALERT: "ALERT!",
    Something_went_wrong: "Quelque chose s'est mal passé",
    SUCCESS: "Succès!",
    ENTER_YOUR_EMAIL: "Insérer e-mail",
    ENTER_YOUR_PASSWORD: "Insérer mot de passe",
    ENTER_YOUR_FIRST_NAME: "Insérer ton le prénom",
    ENTER_VALID_FIRSTNAME: " Merci d'entrer un prénom valide",
    ENTER_YOUR_LAST_NAME: "Insérer ton nom",
    ENTER_VALID_LASTNAME: "Merci d'entrer un nom valide",
    ENTER_YOUR_USER_NAME: "Insérer ton nom d’utilisateur",
    ENTER_VALID_USERNAME: "Merci d'entrer un nom d’utilisateur valide",
    ENTER_YOUR_DATE_OF_BIRTH: "Insérer ta date de naissance",
    ENTER_YOUR_GENDER: "Insérer ton sexe",
    PLEASE_ACCEPT_TERMS_AND_CONDITIONS:
        "Veuillez accepter les termes et conditions",
    PLEASE_SELECT_IF_YOU_ARE_18: "Sélectionne si tu as plus de 13 ans",
    PASSWORD_MUST_BE_BETWEEN_8_AND_12:
        "Mot de passe doit être d'au moins 8 caractères",
    BOTH_PASSWORDS_MUST_BE_SAME: "Les deux mots de passe doivent être identiques",
    PLEASE_ENTER_VALID_EMAIL_ADDRESS: "Insérer email valide",
    PLEASE_ENTER_VALID_BIRTHDATE:
        "Insérer une date de naissance",
    SELECT_YOUR_GENDER: "Sélectionne sexe",
    SELECT_YOUR_JOB_LEVEL: "Sélectionne emploi",
    SELECT_YOUR_EDUCATION: "Sélectionne niveau scolaire",
    SELECT_AN_OPTION: "Sélectionne une option",
    SELECT_YOUR_CITY: "Sélectionne une ville",
    SELECT_YOUR_COUNTRY: "Sélectionne un pays",
    No_cards: "Aucune carte disponible",
    Use_default_card: "Utilise cette carte comme prédéfinie",
    CARD_LIST: "LISTE CARTES",
    ADD_CARD: "AJOUTER CARTE",
    Add_New_Card: "Ajoute nouvelle carte",
    Pay: "Payer",
    Card_Details: "Détails de la carte",
    ACCEPT_TC: "Accepte les Termes et Conditions",
    Delete_Message: "Es-tu sur de vouloir éliminer cette carte ?",
    Logout_Message: "Es-tu sur de vouloir quitter?",
    SORRY_NO_DATA_FOUND: "Désolé, aucune donnée trouvée!",
    NAME: "Nom",
    REMOVE_ALL_NOTIFICATION: "Es-tu certain de vouloir refuser les notifications?",
    Average_Vote: "FanRate",
    PLAYER_NAME: "Nom du joueur",
    Players: "Joueurs",
    Substitute: "Remplaçant",
    Coach: "Entraineur",
    TO_UNLOCK_MATCH: "POUR DEBLOQUER LE MATCH",
    BUY_MATCH_BTN_TEXT: "Débloquer",
    TOKENS_VALUE: "FanCoins",
    SHARE_BTN: "PARTAGER",
    UNLOCK_MATCH: "Tu veux voter plusieurs matches? Monte de niveau en gagnant des points!",
    INVITE_INFO:
        "Salut ! Je voudrais t’inviter sur Fan Rating, clique sur le lien et enregistre ton compte.",
    LEVEL: "Niveau",
    HURRY_UP_VOTE: "Dépêches-toi ! Les votations vont bientôt fermer!",
    MATCH_RESULTS:
        "Les résultats vont être visibles 24h après le match!",
    QUIZ: "QUIZ",
    SELECT_TEAM: "Sélectionne équipe",
    SELECT_YOUR_TEAM: "Sélectionne ton équipe",
    CHANGE_TEAM: "Change équipe",
    CHOOSE_YOUR_TEAM: "Choisi ton équipe",
    INDEX: "INDICE",
    VOTE_FOR_MATCHES: "MATCHES",
    SOMETHING_WENT_WRONG: "Erreur",
    REMOVE_ALL: "Tout éliminer",
    VERIFICATION_SUCCESS: "Vérification réussie.",
    VERIFICATION_FAILED: "Vérification non réussie.",
    GO: "Allez !",
    EMAIL_VERIFICATION: "Vérifier email",
    WELCOME: "Bienvenue !",
    toFanSerie: "sur Fan Rating !",
    KICK_OFF: "C’est bientôt le coup d’envoi !",
    WHY_WAIT: "Pourquoi attendre ?",
    CANCEL: "Annuler",
    OK: "ok",
    UPCOMING_MATCH: "PROCHAIN MATCH!",
    VOTE_ENABLED: "Tu pourras voter ce match une fois terminé !",
    Password_Success: "Mot de passe changé avec succès!",
    VOTING_CONFIRMATION:
        "Confirmer tes bulletins pour {{TEAMA}} et pour {{TEAMB}}? Tu ne pourras plus modifier tes notes après ta confirmation.",
    WINNERS: "FAN WINNER",
    VERIFIED: "C’EST BON, TU ES VERIFIE’!",
    NOT_VERIFIED: " TU N’ES PAS VERIFIE’!",
    FAQ: "Consulte les FAQ",
    HOW_TO_PLAY: "Comment jouer",
    BECOME_TESTER: "Deviens un tester",
    SORRY_THIS_PAGE_IS_NOT_AVAILABLE:
        "Désolé, cette page n’est pas disponible.",
    THE_LINK_YOU_FOLLOWED_MAY_BE_BROKEN:
        "Le lien ne fonctionne pas ou la page n’est plus présente.",
    GO_BACK_TO_FANRATINGWEB: "Retour à FanRatingWeb",
    CONFIRM_REDEEM:
        "Es-tu certain de vouloir racheter {{productName}}? Le code de rachat sera envoyé à ton email enregistrée",
    GOALKEEPER: "GARDIEN DE BUT",
    DEFENDER: "DEFENSEUR",
    MIDFIELDER: "MILIEU",
    FORWARD: "ATTAQUANT",
    COACH: "ENTRAINEUR",
    SIGNUP_EMAIL: " S'inscrire avec e-mail",
    INVITE_AND_EARN: "Invite un amis",
    ADD_COMMENT: "Ajoute un commentaire . . .",
    UNLOCK: "DEBLOQUER",
    PASSWORD_MUST_BE_MINIMUM_OF_8_CHARACTERS:
        "Le mot de passe doit être d’au moins 8 caractères.",
    CHOOSE_FILE: "Choisi un fichier",
    EIGHTEEN_PLUS: "Tu dois avoir plus de 13 ans pour procéder!",
    FIRSTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "Le prénom doit être d’au moins 3 lettres",
    LASTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "Le nom doit être d’au moins 3 lettres",
    USERNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "Le nom utilisateur doit être d’au moins 3 lettres",
    Be_First_to_like: "Soit le premier un mettre un like",
    PROFILE_UPDATED: "Image de ton profil modifiée.",
    APPLE_WARN:
        "Es-tu déjà enregistré avec le compte Apple ? Pour accéder demande un nouveau mot de passe.",
    BUY_MORE_TOKENS: "Achète plus de FanCoins",
    SELECT_ONE_OPTION: "Veuillez sélectionner une option !",
    VALID_DATE: "Veuillez insérer une date valable",
    NOT_LEAP_YEAR: "La date insérée n’est pas valable",
    INVLAID_LEAP_YEAR: "Date de l’année bissextile non valable",
    INVALID_MONTH: "Mois non valable",
    INVALID_YEAR: "Année non valable",
    FUTURE_DATE: "Tu ne peux pas insérer une date future",
    ALTEAST_EIGHTEEN: "Tu dois avoir au moins 13 ans",
    AWARD_REDEEMED: "PRIX RACHETE’ !",
    CONGRATULATIONS_YOU_JUST_EARNED_A_COIN:
        "Congratulations! Tu as gagné un Fan Coin!",
    OFFLINE_TITLE: "Tu es offline",
    OFFLINE_SUB_TITLE: "Ton app est offline",
    OFFLINE_DESC:
        "Contrôle ta connexion à Internet ou tes réglages Wi-Fi",
    OFFLINE_REFRESH_BTN: "Recharger",
    MATCH: "Match",
    POSITION: "Position",
    FAN_WINNERS: "Fan Winners",
    VOTE_NEW: "Vote",
    DEVICE_INFO1: "Tu ne sais pas comment installer Fan Rating sur ton appareil ?",
    DESCTOP_INFO1: "Tu ne sais pas comment installer Fan Rating sur ton appareil ?",
    DEVICE_INFO2: "Découvre comment, en appuyant ci-dessous",
    DESCTOP_INFO2: "Découvrez comment, en appuyant ci-dessous",
    DESCTOP_BTN_NAME: "Clique ici",
    DEVICE_BTN_NAME: "Clique ici",
    NEW_MENU_OPTION: "Installe Fan Rating",


    EARNED_MORE_TOKENS:
        "Tu n'a pas assez de Fan Coins pour ce prix. Gagne-en plus ou achète-les",
    TEASING_ROOM: "Le coin des charrieurs",
    TEASING_ROOM_TITLE: "Le coin des charrieurs",
    CAPTION: "Didascalie",
    MEDIA: "Media",
    ADD_POST: "Charrier",
    READY_TO_SEND: " PRÊT À ENVOYER?",
    DELETE_POST: "Es-tu sur de vouloir supprimer ce post?",
    MY_POST: "Mes posts charrieurs",
    POST_CAPTION: "Insérer didascalie ici ...",
    REPORT_POST: "Signale post",
    REPORT_REASON: "Motivation",
    REASON_PLACEHOLDER: "Ajoute motivation du rapport ....",
    INCREASE_LEVEL: "Augmente ton niveau",
    CHECK_EMAIL:
        "Merci d'avoir racheté cette récompense, vérifie ta boîte de réception pour ton code.",
    ADD_POST_VALIDATION: "Ajouter une image ou une vidéo",
    ADD_CAPTION_VALIDATION: "Ajouter didascalie",
    NO_COMMENT:
        "Aucun commentaire disponible pour le moment. Tu peux être le premier à laisser un commentaire.",
    LEVEL_PRICE: "FanCoins Nécessaires",
    INCREASE_LEVEL1: "AUGMENTE NIVEAU",
    ENTER_REPORT: "Veuillez entrer la raison ",
    EDIT_POST: "Modifie post",
    UPLOAD_FAILED: "Impossible télécharger le file mkv. Sélectionne mp4/webm",
    COMMENT_SCREEN_TITLE: "Commentaires",
    MOST_COMMENTS: "Le plus commenté",
    MOST_LIKES: "Le plus de like",
    MOST_RECENT: "Le plus récent",
    ORDER_BY: "Trier par",
    TEAM_TAG: "Tag équipe",
    SELECT_TEAM_TAG: "Sélectionne tag équipe",
    FIRST_POST:
        "Quel silence ici, fais rire les autres fans avec ton post allumeur !", INVALID_FILE: "type de fichier invalide",
    UPLOAD_DOCUMENT: "TELECHARGE FICHIER",
    SAVE_DOCUMENT: "Sauvegarde document",
    PLEASE_SELECT_FILE: "Veuillez sélectionner le fichier",
    New_Token_key: "Niveau supérieur",
    showMore: "Montre plus",
    reply: "Répondre",
    ALL_VIDEOS: "Tous les vidéos",
    ALL_NEWS: "Toutes les news",
    LIKE: "Like",
    ATTENTION: "ATTENTION!",
    VOTE_ALL_PLAYERS: "Votez tous les joueurs !",
    WELCOME_BACK_ONBOARD: "Bienvenue à bord !",
    SIGN_IN_WITH_EAMIL: "Accède avec email",
    WELCOME_TO_FAN_RATING: "Bienvenue Fan Rating",
    BACK: "Retour",
    NOT_REGISTERED_YET: "Tu n’es pas encore enregistré ?",
    CREATE_AN_ACCOUNT: "Créer compte!",
    JOIN_THE_COMMUNITY_OF_FOOTBALL_FANS: "Rejoins la plus grande communauté où les fans de football sont les protagonistes !",

    CONFIRM: "Confirmé",
    CONTINUE_VOTE: "Confirmer vote",
    NOTE_TWO_TEAMS: "Tu as 2 équipes à voter",
    INSTALL_APP_ON_IPHONE: "Installe sur iPhone",
    INSTALL_APP_ON_ANDROID: "Installe sur Android",

    FAN_COINGS_LEVET_UP_CONFIRM_MESSAGE: "Besoin de {level_price} FanCoins pour passer au niveau supérieur. Sur de vouloir continuer?",
    FAN_SUBSCRIBER_TV: "Abonné Télé",
    FAN_SEASON_TICKET: "Abonné stade",
    FAN_OCCA: "De temps en temps",
    PROFILE_UPDATE_MESSAGE: "Ton profil a été modifié",
    Phone: "Téléphone",
    ENTER_YOUR_PHONE: "Entrez votre téléphone.",
    // new words 3/10/2023
    FUN_VERSE: 'FunVerse',
    REGISTER: 'Enregistrer'
};
