export const GeLanguage = {
    TEAMLIST_TITLE: `SELEZIONA LA TUA\nSQUADRA`,
    NOTIFICATION: "Notifikationen",
    TEAMLIST_DESC:
        "Bedenken Sie, dass Sie es nicht mehr ändern können, es wird die einzige Mannschaft sein, für die Sie stimmen",
    TEAMLIST_DESC2: "über die Sie kostenlos Nachrichten erhalten möchten",
    NEXT: "Anhang",
    NEXT_2: "Demnächst unter",
    TIFA: "ANZEIGE",
    RATE_IT: "ABSTIMMEN",
    WIN: "DIE SEITE VINCI",
    ALL: "Das Tutti",
    CURRENT: "In Bearbeitung",
    PAST: "Dein Zeugnis",
    RATE: "ABSTIMMEN",
    VOTE: "ABSTIMMEN",
    VIEW: "Überprüfen",
    ACHIEVEMENTS: "DIE SEITE VINCI",
    PRIME_AMAZON: "AMAZON PREISE",
    PARTNERS_PRIZES: "PARTNERAUSZEICHNUNG",
    LIMITED_AVAILABILITY: "LIMITIERTE VERFÜGBARKEIT",
    VIEW_ALL: "Alle anzeigen",
    FORGOT_PASSWORD_CAPITAL: "KENNWORT VERGESSEN?",
    FORGOT_PASSWORD: "KENNWORT VERGESSEN",
    Forgot_Password: "KENNWORT VERGESSEN",
    NEW_PASSWORD: "Das neue Passwort",
    CONFIRM_NEW_PASSWORD: "Bestätigen Sie das neue Passwort",
    SAVE_PASSWORD: "Kennwort speichern",
    LOGIN: "Anmelden",
    EDIT_PROFILE: "Profil editieren",
    SIGN_OUT: "Ausloggen",
    SIGN_IN: "Anmeldung",
    SIGN_IN_CAPITAL: "Anmeldung",
    SIGN_UP: "Registrieren Sie sich",
    YOUR_TOKENS: "Deine Fan-Münzen",
    SIGN_UP_CAPITAL: "Registrieren Sie sich",
    TOKEN: "Fan Münzen",
    POINTS: "Punkte",
    EMAIL: "E-mail",
    PASSWORD: `Passwort`,
    OR: "OR",
    SIGN_IN_WITH_APPLE: "Anmelden mit Apple",
    SIGN_IN_WITH_FACEBOOK: "Mit Facebook anmelden",
    SIGN_IN_WITH_GOOGLE: "Anmelden mit Google",
    SIGN_UP_WITH_APPLE: "Registrierung bei Apple",
    // SIGN_Up_WITH_FACEBOOK: "Registrierung bei Facebook",
    // SIGN_Up_WITH_GOOGLE: "Registrierung bei Google",
    NO_ACCOUNT: "Non avete ancora un account?",
    HAVE_ACCOUNT: `Besitzen Sie bereits ein Konto?`,
    FIRST_NAME: "Bezeichnung",
    LAST_NAME: "Nachname",
    GENDER: "Geschlecht",
    DATE_OF_BIRTH: "Geburtsjahr",
    USERNAME: "Benutzername",
    CREATE_ACCOUNT: "Konto erstellen",
    SIGN_UP_WITH_FACEBOOK: "schreibe Ihnen mit Facebook",
    SIGN_UP_WITH_GOOGLE: "Mit Google zusammenarbeiten",
    MALE: "Männchen",
    FEMALE: "Weibliche",
    OTHER: "Weiter",
    THANK_YOU_FOR_SUBMITTING: `VIELEN DANK FÜR DIE ZUSENDUNG`,
    PASSWORD_CHANGE_SUCCESSFULY: "PASSWORT ERFOLGREICH VERÄNDERT",
    PASSWORD_CHANGE_SUCCESSFUL: "PASSWORT ERFOLGREICH VERÄNDERT",
    PREVIOUS: "Vorige",
    SUBMIT: "Senden Sie",
    FINISH: "Ergebnis ansehen",
    SKIP: "Überspringen",
    QUIZ_INSTRUCTIONS: "QUIZ-ANWEISUNGEN",
    QUIZ_RESULT: "IHR RESULTAT",
    YOUR_SCORE: "IHR RATING",
    EARNED_TOKENS: "FÄCHERMÜNZEN VINTI",
    CLOSE: "Schließen Sie",
    FISCAL_CODE: "Steuerkennzeichen",
    EDUCATION: "Schulbildung",
    CITY: "Städte",
    PROFESSION: "Beruf",
    SAVE_PROFILE: "Profil sichern",
    YOUR_PROFILE: "Ihr Profil",
    CHANGE_PASSWORD: "DAS PASSWORT ÄNDERN",
    CHEERS: "ANZEIGE",
    STREAMS: "LIVE",
    FAN_RATING_TV: "FAN RATING TV",
    NEWS: "DER BLOG",
    FILTER_BY: "Gefiltert nach",
    PRIVACY_POLICY: "Datenschutzerklärung",
    TERMS_AND_CONDITION: "Bedingungen und Voraussetzungen",
    MISSION: "Aufgabe",
    HELP: "Regelungen und FAQ",
    CONTACT_US: "Kontaktaufnahme",
    RANKING: "Klassifizierung",
    BUY_PACKAGE: "Kaufe das Paket",
    THANK_YOU_FOR_REVIEW: "VIELEN DANK FÜR DIE ZUSENDUNG",
    THANK_YOU_FOR_VOTING:
        "VIELEN DANK FÜR DIE ZUSENDUNG! Ihr Ergebnis ist innerhalb von 24 Stunden nach Beendigung des Spiels verfügbar. Schau wieder vorbei!",
    COUNTRY: "Das Land",
    WATCH_ON: "Anschauen auf DAZN",
    GO_TO_SAN_SIRO_STADIUM: "Zum San-Siro-Stadion",
    GIFT_CARD: "Die Geschenkkarte",
    DISCOUNT_CODES: "Ermäßigte Codes",
    PRIME_SPECIAL: "Sonderpreise",
    GOAL: "Tore",
    AVERAGE_FAN_RATING: "Medien Bewertung Fan",
    PLAYED_MATCHES: "Ausgetragene Spiele",
    RANK: "Klassifizierung",
    DESCRIPTION: "Beschreibung",
    ACCEPT_TERMS_AND_CONDITION: "Akzeptieren Sie die Allgemeinen Geschäftsbedingungen",
    CONGRATULATION: "Herzlichen Glückwunsch",
    YOUR_RATE_CARD: "ÜBERPRÜFEN SIE IHR ZEUGNIS",
    REDEEM_FOR_TOKENS: "Einlösen mit Fan-Münzen",
    LIVE: "LIVE",
    POSTED_ON: "Eingestellt am",
    MESSAGE: "Nachricht",
    IN_PROGRESS: "In Bearbeitung",
    CONCLUDED: "Dein Zeugnis",
    ABOUT_US: "Über uns",
    MY_TEAM: "Meine Mannschaft",
    FAN: "Lüfter",
    TV_SUBSCRIBER: "Fernsehabonnent",
    STADIUM_SUBSCRIBER: "Abonnent des Stadions",
    OCCASIONAL: "Gelegentliche",
    JOB_LEVEL: "Beruf",
    YES_LETS_START_CHEERING: "Ja, lasst uns anfangen zu jubeln",
    NO_I_WANT_TO_CHANGE: "Nein, ich möchte mich ändern",
    Look_at_all: "Seht alle her",
    Share_review: "Teilen Sie die Reportkarte mit Ihren Freunden",
    Find_out: "Finden Sie heraus, ob Sie gewonnen haben von",
    remaining: "verbleibende",
    how_to_play: "Wie spielen Sie?",
    UPLOAD_A_PHOTO: "FOTO HOCHLADEN",
    SAVE_PHOTO: "Foto speichern",
    GAMES_PLAYED: "Ausgetragene Spiele",
    NATIONALITY: "Nationalität",
    HEIGHT: "Höhe",
    WEIGHT: "Gewicht",
    I_AM_18_YEARS_OLD: "Ich bin 13 Jahre alt",
    REQUIRED_TO_MAKE_IN_APP_PURCHASES_AND_ACCESS_THE_REWARDS_CATALOG:
        "Erforderlich, um In-App-Käufe zu tätigen und auf den Fankatalog zuzugreifen",
    SELECT_YOUR_HEART_TEAM: "WÄHLEN SIE IHRE LIEBLINGSMANNSCHAFT",
    QUIZ_CONGRATULATIONS: `Herzlichen Glückwunsch, Sie sind der Quiz-Gewinner! Du hast alle Fragen richtig beantwortet!`,
    QUIZ_TRY_AGAIN:
        "Du musst dich etwas mehr vorbereiten, aber keine Sorge, das kannst du beim nächsten Quiz wieder wettmachen!",
    CONGRATULATIONS: "Herzlichen Glückwunsch!",
    BETTER_LUCK_NEXT_TIME: "Nächstes Mal mehr Glück",
    INVITE_A_FRIEND_AND_RECEIVE_25_TOKENS:
        "Lade einen Freund ein und erhält 25 Fan-Münzen",
    INVITE_FRIENDS_DESCRIPTION:
        "Du kannst einen Freund einladen, sich für Fan Rating zu registrieren und erhältst 25 Fanmünzen. Denken Sie daran, dass Sie Fan-Münzen erhalten, wenn der Nutzer die Registrierung über den Einladungslink abgeschlossen hat.",
    INVITE_A_FRIEND: "Einladen eines Freundes",
    INVITE_AND_REFER: "Einladen eines Freundes",
    BUY_TOKENS: "Fan-Münzen kaufen",
    TOKENS: "Fan Münzen",
    MAKE_A_PAYMENT: "Eine Zahlung durchführen",
    TRANSACTION_LIST: "Liste der Transaktionen",
    VOTE_other_matches: "VOTE andere Spiele",
    LIKES: "Gefällt",
    SURVEY_INSTRUCTIONS: "BEFRAGUNGSANWEISUNGEN",
    SURVEY: "UMFRAGE",
    SURVEY_COMPLETED: "Wir danken Ihnen! Wir haben Ihre Stellungnahme erhalten.",
    RESET_PASSWORD: "Kennwort zurücksetzen",
    WARNING: "Warnhinweis!",
    OOPS: "Oups!",
    ALERT: "Warne sie!",
    Something_went_wrong: "Etwas ist schiefgelaufen",
    SUCCESS: "Erfolgreich!",
    ENTER_YOUR_EMAIL: "Ihre E-Mail eingeben",
    ENTER_YOUR_PASSWORD: "Geben Sie Ihr Kennwort ein",
    ENTER_YOUR_FIRST_NAME: "Geben Sie Ihre E-Mail-Adresse ein",
    ENTER_VALID_FIRSTNAME: "Bitte einen gültigen Namen eingeben",
    ENTER_YOUR_LAST_NAME: "Bitte geben Sie Ihren Nachnamen an",
    ENTER_VALID_LASTNAME: "Bitte geben Sie einen gültigen Nachnamen an",
    ENTER_YOUR_USER_NAME: "Geben Sie Ihren Benutzernamen an",
    ENTER_VALID_USERNAME: "Bitte geben Sie einen gültigen Benutzernamen ein",
    ENTER_YOUR_DATE_OF_BIRTH: "Geben Sie Ihr Geburtsdatum an",
    ENTER_YOUR_GENDER: "Geben Sie Ihr Geschlecht an",
    PLEASE_ACCEPT_TERMS_AND_CONDITIONS:
        "Bitte akzeptieren Sie die Bedingungen und Konditionen",
    PLEASE_SELECT_IF_YOU_ARE_18: "Wählen Sie, ob Sie 18 Jahre alt sind",
    PASSWORD_MUST_BE_BETWEEN_8_AND_12:
        "Das Kennwort muss mindestens 8 Zeichen lang sein.",
    BOTH_PASSWORDS_MUST_BE_SAME: "Beide Passwörter müssen identisch sein",
    PLEASE_ENTER_VALID_EMAIL_ADDRESS: "Bitte geben Sie eine gültige E-Mail Adresse ein",
    PLEASE_ENTER_VALID_BIRTHDATE:
        "Bitte geben Sie ein gültiges Geburtsdatum an",
    SELECT_YOUR_GENDER: "Bitte wählen Sie Ihr Geschlecht",
    SELECT_YOUR_JOB_LEVEL: "Wählen Sie Ihre Arbeit",
    SELECT_YOUR_EDUCATION: "Wählen Sie Ihre Schulung",
    SELECT_AN_OPTION: "Eine Option auswählen",
    SELECT_YOUR_CITY: "Wählen Sie Ihre Stadt",
    SELECT_YOUR_COUNTRY: "Bitte wählen Sie Ihr Land",
    No_cards: "Keine Karte verfügbar",
    Use_default_card: "Diese Karte als Standard benutzen",
    CARD_LIST: "LISTE DER KARTEN",
    ADD_CARD: "EINGEBEN",
    Add_New_Card: "Neue Karte einfügen",
    Pay: "Bezahlen",
    Card_Details: "Karten-Extreme",
    ACCEPT_TC: "Akzeptieren Sie die Allgemeinen Geschäftsbedingungen",
    Delete_Message: "Sind Sie sicher, dass Sie diese Karte streichen wollen?",
    Logout_Message: "Sind Sie sicher, dass Sie ausgehen wollen?",
    SORRY_NO_DATA_FOUND: "Leider keine Daten gefunden!",
    NAME: "Bezeichnung",
    REMOVE_ALL_NOTIFICATION: "Sind Sie sich sicher, dass Sie alle Benachrichtigungen entfernen möchten?",
    Average_Vote: "Medien",
    PLAYER_NAME: "Name des Spieler",
    Players: "Spieler",
    Substitute: "Stellvertretungen",
    Coach: "Trainerin",
    TO_UNLOCK_MATCH: "ZUM FREISCHALTEN DES SPIELS",
    BUY_MATCH_BTN_TEXT: "Freischaltung",
    TOKENS_VALUE: "Fan Münzen",
    SHARE_BTN: "TEILEN",
    UNLOCK_MATCH: "Willst du mehr Spiele bewerten? Erhöhe dein Level, indem du Punkte sammelst!",
    INVITE_INFO:
        "Hallo, ich möchte Sie zu Fan Rating einladen, klicken Sie auf diesen Link und registrieren Sie Ihr Konto.",
    LEVEL: "Niveau",
    HURRY_UP_VOTE: "Beeilen Sie sich! Die Abstimmung wird bald beendet sein!",
    MATCH_RESULTS:
        "Die Ergebnisse sind 24 Stunden nach Ende des Spiels zu sehen!",
    QUIZ: "QUIZ",
    SELECT_TEAM: "Team wählen",
    SELECT_YOUR_TEAM: "Wählen Sie Ihre Mannschaft",
    CHANGE_TEAM: "Team ändern",
    CHOOSE_YOUR_TEAM: "Wählen Sie Ihr Team",
    INDEX: "INHALT",
    VOTE_FOR_MATCHES: "PARTITE",
    SOMETHING_WENT_WRONG: "Etwas ist schiefgelaufen",
    REMOVE_ALL: "Alle entfernen",
    VERIFICATION_SUCCESS: "Ihr Konto wurde erfolgreich überprüft.",
    VERIFICATION_FAILED: "Ihr Konto wurde zurückgewiesen.",
    GO: "Weiter",
    EMAIL_VERIFICATION: "E-Mail-Überprüfung",
    WELCOME: "Willkommen",
    toFanSerie: "zur Fan-Bewertung der Serie A!",
    KICK_OFF: "Nur noch wenige Momente bis zum Anpfiff",
    WHY_WAIT: "Doch warum warten?",
    CANCEL: "Abbestellen",
    OK: "OK",
    UPCOMING_MATCH: "NÄCHSTES SPIEL!",
    VOTE_ENABLED: "Sie können für dieses Spiel abstimmen, wenn es beendet ist!",
    Password_Success: "PASSWORT ERFOLGREICH VERÄNDERT",
    VOTING_CONFIRMATION:
        "Möchten Sie Ihre Noten für {{TEAMA}} und {{TEAMB}} bestätigen? Nach der Bestätigung können Sie Ihre Ratings nicht mehr bearbeiten.",
    WINNERS: "BLICK AUF FAN-GEWINNER",
    VERIFIED: "SIE SIND VERIFIZIERT!",
    NOT_VERIFIED: "SIE SIND NICHT VERIFIZIERT!",
    FAQ: "Sehen Sie sich die FAQ an",
    HOW_TO_PLAY: "Lernen Sie das Spiel",
    BECOME_TESTER: "Werden Sie jetzt Tester",
    SORRY_THIS_PAGE_IS_NOT_AVAILABLE:
        "Leider ist diese Seite nicht verfügbar.",
    THE_LINK_YOU_FOLLOWED_MAY_BE_BROKEN:
        "Der Link, dem Sie gefolgt sind, ist vielleicht defekt oder die Seite wurde entfernt.",
    GO_BACK_TO_FANRATINGWEB: "Zurück zu FanRatingWeb",
    CONFIRM_REDEEM:
        "Sind Sie sicher, dass Sie {{Produktname}} zurücknehmen möchten? Der Code wird Ihnen an die E-Mail-Adresse geschickt, die Sie bei der Registrierung angegeben haben.",
    GOALKEEPER: "PORTER",
    DEFENDER: "VERTEIDIGER",
    MIDFIELDER: "MITTELFELDSPIELER",
    FORWARD: "Vorwärts",
    COACH: "TRAINERIN",
    SIGNUP_EMAIL: "Anmeldung mit E-Mail",
    INVITE_AND_EARN: "Einladen von Freunden",
    ADD_COMMENT: "Ein Kommentar hinzufügen . . .",
    UNLOCK: "UNBLOCKIEREN",
    PASSWORD_MUST_BE_MINIMUM_OF_8_CHARACTERS:
        "Das Kennwort muss aus mindestens 8 Zeichen bestehen.",
    CHOOSE_FILE: "Wählen Sie eine Datei",
    EIGHTEEN_PLUS: "Zur Teilnahme müssen Sie über 18 Jahre alt sein.!",
    FIRSTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "der Name muss mindestens 3 Buchstaben haben",
    LASTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "der Nachname muss aus mindestens 3 Buchstaben bestehen",
    USERNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "der Benutzername muss mindestens 3 Buchstaben lang sein",
    Be_First_to_like: "Du kannst der Erste sein, dem es gefällt",
    PROFILE_UPDATED: "Profilbild wurde aktualisiert.",
    APPLE_WARN:
        "Sie haben sich bereits mit einem Apple Account registriert? Bitte fordern Sie ein neues Passwort an, um sich anzumelden.",
    BUY_MORE_TOKENS: "Mehr Wertmarken kaufen",
    SELECT_ONE_OPTION: "Selezionare una delle opzioni seguenti!",
    VALID_DATE: "Bitte geben Sie ein gültiges Datum an",
    NOT_LEAP_YEAR: "Das angegebene Datum ist kein Schaltjahr",
    INVLAID_LEAP_YEAR: "Unzulässiges Schaltjahr-Datum",
    INVALID_MONTH: "Monat ungültig",
    INVALID_YEAR: "Jahr ungültig",
    FUTURE_DATE: "Sie können kein künftiges Datum eingeben",
    ALTEAST_EIGHTEEN: "Du musst mindestens 13 Jahre alt sein",
    AWARD_REDEEMED: "PREIS ERLÖST!",
    CONGRATULATIONS_YOU_JUST_EARNED_A_COIN:
        "Herzlichen Glückwunsch! Du hast dich mit einer Fanmünze belohnt!",
    OFFLINE_TITLE: "Sie sind im Offline-Modus",
    OFFLINE_SUB_TITLE: "Ihre Anwendung befindet sich im Offline-Modus",
    OFFLINE_DESC:
        "Versuchen Sie, die Einstellungen Ihrer Internetverbindung oder Ihres Wi-Fi zu überprüfen",
    OFFLINE_REFRESH_BTN: "nachladen",
    MATCH: "Spiel",
    POSITION: "Stellung",
    FAN_WINNERS: "Fan-GewinnerInnen",
    VOTE_NEW: "Abstimmen",
    DEVICE_INFO1: "Sie wissen nicht, wie Sie den Fan Rating auf dem Gerät installieren können?",
    DESCTOP_INFO1: "Sie wissen nicht, wie Sie den Fan Rating auf dem Gerät installieren können?",
    DEVICE_INFO2: "Tippen Sie hier, um mehr darüber zu erfahren",
    DESCTOP_INFO2: "Klicken Sie hier, um zu sehen, wie das geht",
    DESCTOP_BTN_NAME: "Klicken Sie hier",
    DEVICE_BTN_NAME: "Tippen Sie hier",
    NEW_MENU_OPTION: "Lüfterleistung installieren",
    EARNED_MORE_TOKENS:
        "Du hast noch nicht genug Fanmünzen für diesen Preis. Verdiene mehr oder kaufe sie",
    TEASING_ROOM: "Mock Gemeinschaft",
    TEASING_ROOM_TITLE: "Spöttelecke",
    CAPTION: "Untertitel",
    MEDIA: "Medien",
    ADD_POST: "Aufklappen",
    READY_TO_SEND: "BEREIT, ES ZU VERSENDEN?",
    DELETE_POST: "Sind Sie sicher, dass dieser Beitrag gelöscht werden soll?",
    MY_POST: "Mein Gespött",
    POST_CAPTION: "Bildunterschrift hier eingeben...",
    REPORT_POST: "Diesen Beitrag berichten",
    REPORT_REASON: "Das Motiv",
    REASON_PLACEHOLDER: "Grund für Berichterstattung hinzufügen....",
    INCREASE_LEVEL: "Erhöhe dein Niveau",
    CHECK_EMAIL:
        "Vielen Dank, dass ihr diesen Preis eingelöst habt. Bitte prüft nach, ob ihr den Code in eurer Mail findet.",
    ADD_POST_VALIDATION: "Bild oder Video hinzuzufügen",
    ADD_CAPTION_VALIDATION: "Untertitel hinzufügen",
    NO_COMMENT:
        "Zur Zeit keine Kommentare verfügbar. Sie können der erste sein, der eine Bemerkung hinterlässt.",
    LEVEL_PRICE: "PREIS",
    INCREASE_LEVEL1: "NIVEAU AUF",
    ENTER_REPORT: "Bitte geben Sie das Motiv ein",
    EDIT_POST: "Beitrag editieren",
    UPLOAD_FAILED: "Eine mkv-Datei kann nicht hochgeladen werden. Wählen Sie mp4/webm",
    COMMENT_SCREEN_TITLE: "Kommentare",
    MOST_COMMENTS: "Meist kommentiert",
    MOST_LIKES: "Mehr mag",
    MOST_RECENT: "Neueste",
    ORDER_BY: "Sortieren nach",
    TEAM_TAG: "Team-Marken",
    SELECT_TEAM_TAG: "Team-Tag wählen",
    FIRST_POST:
        "Wie ruhig hier, mit deinem ersten Spott bringst du andere Fans zum Lachen",
    INVALID_FILE: "unzulässiger Dateityp",
    UPLOAD_DOCUMENT: "DOKUMENT HOCHLADEN",
    SAVE_DOCUMENT: "Dokument speichern",
    PLEASE_SELECT_FILE: "Wählen Sie bitte die Datei",
    New_Token_key: "Eine Stufe höher steigen",
    showMore: "Siehe mehr",
    reply: "Antworten",
    ALL_VIDEOS: "Sämtliche Videos",
    ALL_NEWS: "Alle News",
    LIKE: "Wie",
    ATTENTION: "ACHTUNG!",
    VOTE_ALL_PLAYERS: "Geben Sie eine Stimme für alle Spieler ab! ",
    WELCOME_BACK_ONBOARD: "Herzlich willkommen zurück an Bord!",
    SIGN_IN_WITH_EAMIL: "Mit Email anmelden",
    WELCOME_TO_FAN_RATING: "Willkommen bei der Fan-Bewertung",
    BACK: "Rücken",
    NOT_REGISTERED_YET: "Sie sind noch nicht registriert? ",
    CREATE_AN_ACCOUNT: "Ein Konto erstellen!",
    JOIN_THE_COMMUNITY_OF_FOOTBALL_FANS: "Werden auch Sie Mitglied der größten Gemeinschaft von Fußballfans!",

    CONFIRM: "Confirm",
    CONTINUE_VOTE: "Bestätigen",
    NOTE_TWO_TEAMS: "Bestätigen Sie eine Abstimmung",
    INSTALL_APP_ON_IPHONE: "Im iPhone installieren",
    INSTALL_APP_ON_ANDROID: "In Android installieren",

    FAN_COINGS_LEVET_UP_CONFIRM_MESSAGE: "Du benötigst {level_price} Fan Coins, um aufzusteigen. Willst du wirklich weitermachen?",
    FAN_SUBSCRIBER_TV: "Abonnenten-TV",
    FAN_SEASON_TICKET: "Stadionpass",
    FAN_OCCA: "Gelegentlich",
    PROFILE_UPDATE_MESSAGE: "Ihr Profil wurde geändert",
    Phone: "Telefon",
    ENTER_YOUR_PHONE: "Geben Sie Ihr Telefon ein.",
    // new words 3/10/2023
    FUN_VERSE: 'FunVerse',
    REGISTER: 'Registrieren'
};
