export const ItLanguage = {
  TEAMLIST_TITLE: `SELEZIONA LA TUA\nSQUADRA`,
  NOTIFICATION: "Notifiche",
  TEAMLIST_DESC:
    "Ricorda che non potrai più cambiarla, sarà l'unica squadra che voterai",
  TEAMLIST_DESC2: "gratuitamente e su cui riceverai news",
  NEXT: "Avanti",
  NEXT_2: "Prossima",
  TIFA: "TIFA",
  RATE_IT: "VOTA",
  WIN: "VINCI",
  ALL: "Tutti",
  CURRENT: "In Corso",
  PAST: "Le tue pagelle",
  RATE: "VOTA",
  VOTE: "Vota",
  VIEW: "Guarda",
  ACHIEVEMENTS: "VINCI",
  PRIME_AMAZON: "PREMI AMAZON",
  PARTNERS_PRIZES: "PREMI DEI PARTNER",
  LIMITED_AVAILABILITY: "DISPONIBILITA LIMITATA",
  VIEW_ALL: "Guarda tutti",
  FORGOT_PASSWORD_CAPITAL: "PASSWORD DIMENTICATA?",
  FORGOT_PASSWORD: "PASSWORD DIMENTICATA",
  Forgot_Password: "Password dimenticata?",
  NEW_PASSWORD: "Nuova Password",
  CONFIRM_NEW_PASSWORD: "Conferma Nuova Password",
  SAVE_PASSWORD: "Salva Password",
  LOGIN: "Login",
  EDIT_PROFILE: "Modifica Profilo",
  SIGN_OUT: "Disconnetti",
  SIGN_IN: "Accedi",
  SIGN_IN_CAPITAL: "ACCEDI",
  SIGN_UP: "Registrati",
  YOUR_TOKENS: "l tuoi FanCoins",
  SIGN_UP_CAPITAL: "REGISTRATI",
  TOKEN: "FanCoins",
  POINTS: "Punti",
  EMAIL: "E-mail",
  PASSWORD: `Password`,
  OR: "OPPURE",
  SIGN_IN_WITH_APPLE: "Accedi con Apple",
  SIGN_IN_WITH_FACEBOOK: "Accedi con Facebook",
  SIGN_IN_WITH_GOOGLE: "Accedi con Google",
  SIGN_UP_WITH_APPLE: "Registrati con Apple",
  // SIGN_Up_WITH_FACEBOOK: "Registrati con Facebook",
  // SIGN_Up_WITH_GOOGLE: "Registrati con Google",
  NO_ACCOUNT: "Non hai ancora un account?",
  HAVE_ACCOUNT: `Hai già un account?`,
  FIRST_NAME: "Nome",
  LAST_NAME: "Cognome",
  GENDER: "Genere",
  DATE_OF_BIRTH: "Data di nascita",
  USERNAME: "Nome utente",
  CREATE_ACCOUNT: "Crea Account",
  SIGN_UP_WITH_FACEBOOK: "Iscriviti con Facebook",
  SIGN_UP_WITH_GOOGLE: "Iscriviti con Google",
  MALE: "Maschio",
  FEMALE: "Femmina",
  OTHER: "Altro",
  THANK_YOU_FOR_SUBMITTING: `GRAZIE PER L'INVIO`,
  PASSWORD_CHANGE_SUCCESSFULY: "PASSWORD CAMBIATA CON SUCCESSO",
  PASSWORD_CHANGE_SUCCESSFUL: "PASSWORD CAMBIATA CON SUCCESSO",
  PREVIOUS: "Precedente",
  SUBMIT: "Invia",
  FINISH: "Guarda Risultato",
  SKIP: "Salta",
  QUIZ_INSTRUCTIONS: "ISTRUZIONI DEL QUIZ",
  QUIZ_RESULT: "IL TUO RISULTATO",
  YOUR_SCORE: "IL TUO PUNTEGGIO",
  EARNED_TOKENS: "FANCOINS VINTI",
  CLOSE: "Chiudi",
  FISCAL_CODE: "Codice fiscale",
  EDUCATION: "Formazione scolastica",
  CITY: "Città",
  PROFESSION: "Professione",
  SAVE_PROFILE: "Salva profilo",
  YOUR_PROFILE: "il tuo Profilo",
  CHANGE_PASSWORD: "CAMBIA PASSWORD",
  CHEERS: "TIFA",
  STREAMS: "IN DIRETTA",
  FAN_RATING_TV: "FAN RATING TV",
  NEWS: "IL BLOG",
  FILTER_BY: "Filtra per",
  PRIVACY_POLICY: "Privacy Policy",
  TERMS_AND_CONDITION: "Termini e Condizioni",
  MISSION: "Mission",
  HELP: "Regolamento e FAQ",
  CONTACT_US: "Contattaci",
  RANKING: "Classifica",
  BUY_PACKAGE: "Acquista il pacchetto",
  THANK_YOU_FOR_REVIEW: "GRAZIE PER L'INVIO",
  THANK_YOU_FOR_VOTING:
    "Grazie per l'invio! Il tuo punteggio sarà disponibile in 24 ore dalla fine della partita. Torna a controllare!",
  COUNTRY: "Paese",
  WATCH_ON: "Guarda in TV",
  GO_TO_SAN_SIRO_STADIUM: "Vai allo Stadio",
  GIFT_CARD: "Gift Card",
  DISCOUNT_CODES: "Codici Sconto",
  PRIME_SPECIAL: "Premi Speciali",
  GOAL: "Gol",
  AVERAGE_FAN_RATING: "FanRate",
  PLAYED_MATCHES: "Partite giocate",
  RANK: "Classifica",
  DESCRIPTION: "Descrizione",
  ACCEPT_TERMS_AND_CONDITION: "Accetta Termini e Condizioni",
  CONGRATULATION: "Congratulazioni",
  YOUR_RATE_CARD: "GUARDA LA TUA PAGELLA",
  REDEEM_FOR_TOKENS: "Riscatta con FanCoins",
  LIVE: "IN DIRETTA",
  POSTED_ON: "Postato il",
  MESSAGE: "Messaggio",
  IN_PROGRESS: "In Corso",
  CONCLUDED: "Le tue pagelle",
  ABOUT_US: "Chi siamo",
  MY_TEAM: "La mia squadra",
  FAN: "Tifoso",
  TV_SUBSCRIBER: "Abbonato TV",
  STADIUM_SUBSCRIBER: "Abbonato Stadio",
  OCCASIONAL: "Occasionale",
  JOB_LEVEL: "Professione",
  YES_LETS_START_CHEERING: "Sì! Iniziamo a tifare",
  NO_I_WANT_TO_CHANGE: "No, voglio cambiare",
  Look_at_all: "Guarda tutti",
  Share_review: "Condividi La Pagella con i tuoi Amici",
  Find_out: "Scopri se hai vinto tra",
  remaining: "rimanente",
  how_to_play: "Come si gioca?",
  UPLOAD_A_PHOTO: "CARICA UNA FOTO",
  SAVE_PHOTO: "Salva foto",
  GAMES_PLAYED: "Partite giocate",
  NATIONALITY: "Nazionalità",
  HEIGHT: "Altezza",
  WEIGHT: "Peso",
  I_AM_18_YEARS_OLD: "Ho 13 anni compiuti",
  REQUIRED_TO_MAKE_IN_APP_PURCHASES_AND_ACCESS_THE_REWARDS_CATALOG:
    "Necessario per effettuare acquisti in-app e accedere al Fan Catalogo",
  SELECT_YOUR_HEART_TEAM: "SELEZIONA LA TUA SQUADRA DEL CUORE",
  QUIZ_CONGRATULATIONS: `Complimenti, sei il Quiz Winner! Hai risposto correttamente a tutte le domande!`,
  QUIZ_TRY_AGAIN:
    "Devi prepararti un po' di più ma non temere, potrai rifarti al prossimo quiz!",
  CONGRATULATIONS: "Congratulazioni!",
  BETTER_LUCK_NEXT_TIME: "La prossima volta sarai più fortunato",
  INVITE_A_FRIEND_AND_RECEIVE_25_TOKENS:
    "invita un amico e ricevi 25 FanCoins",
  INVITE_FRIENDS_DESCRIPTION:
    "Puoi invitare un amico a registrarsi su Fan Rating e ricevere 25 FanCoins. Riceverai i FanCoins una volta che l’utente avrà completato la registrazione tramite il link d’invito.",
  INVITE_A_FRIEND: "Invita un amico",
  INVITE_AND_REFER: "Invita un amico",
  BUY_TOKENS: "Acquista FanCoins",
  TOKENS: "FanCoins",
  MAKE_A_PAYMENT: "Fai un pagamento",
  TRANSACTION_LIST: "Elenco delle transazioni",
  VOTE_other_matches: "VOTA altre partite",
  LIKES: "Mi Piace",
  SURVEY_INSTRUCTIONS: "ISTRUZIONI PER IL SONDAGGIO",
  SURVEY: "SONDAGGIO",
  SURVEY_COMPLETED: "Grazie! La tua opinione è stata ricevuta.",
  RESET_PASSWORD: "Resetta la password",
  WARNING: "Warning!",
  OOPS: "Oops!",
  ALERT: "Allert!",
  Something_went_wrong: "Qualcosa è andato storto",
  SUCCESS: "Successo!",
  ENTER_YOUR_EMAIL: "Inserisci la tua email",
  ENTER_YOUR_PASSWORD: "Inserisci la tua password",
  ENTER_YOUR_FIRST_NAME: "Inserisci il tuo nome",
  ENTER_VALID_FIRSTNAME: "Si prega di inserire un nome valido",
  ENTER_YOUR_LAST_NAME: "Inserire il cognome",
  ENTER_VALID_LASTNAME: "Si prega di inserire un cognome valido",
  ENTER_YOUR_USER_NAME: "Inserisci il tuo nome utente",
  ENTER_VALID_USERNAME: "Per favore inserisci un nome utente valido",
  ENTER_YOUR_DATE_OF_BIRTH: "Inserisci la tua data di nascita",
  ENTER_YOUR_GENDER: "Inserisci il tuo genere",
  PLEASE_ACCEPT_TERMS_AND_CONDITIONS:
    "Si prega di accettare termini e condizioni",
  PLEASE_SELECT_IF_YOU_ARE_18: "Seleziona se hai 13 anni",
  PASSWORD_MUST_BE_BETWEEN_8_AND_12:
    "La password deve essere di almeno 8 caratteri",
  BOTH_PASSWORDS_MUST_BE_SAME: "Entrambe le password devono essere uguali",
  PLEASE_ENTER_VALID_EMAIL_ADDRESS: "Inserisci indirizzo email valido",
  PLEASE_ENTER_VALID_BIRTHDATE:
    "Si prega di inserire una data di nascita valida",
  SELECT_YOUR_GENDER: "Seleziona il tuo genere",
  SELECT_YOUR_JOB_LEVEL: "Seleziona il tuo lavoro",
  SELECT_YOUR_EDUCATION: "Seleziona la tua formazione",
  SELECT_AN_OPTION: "Seleziona un'opzione",
  SELECT_YOUR_CITY: "Seleziona la tua città",
  SELECT_YOUR_COUNTRY: "Seleziona il tuo paese",
  No_cards: "Nessuna carta disponibile",
  Use_default_card: "Usa questa carta come predefinita",
  CARD_LIST: "ELENCO CARTE",
  ADD_CARD: "INSERISCI",
  Add_New_Card: "Aggiungi nuova carta",
  Pay: "Paga",
  Card_Details: "Estremi della carta",
  ACCEPT_TC: "Accetta Termini e Condizioni",
  Delete_Message: "Sei sicuro di voler eliminare questa carta?",
  Logout_Message: "Sei sicuro di voler uscire?",
  SORRY_NO_DATA_FOUND: "Spiacenti, nessun dato trovato!",
  NAME: "Nome",
  REMOVE_ALL_NOTIFICATION: "Sei sicuro di voler rimuovere tutte le notifiche?",
  Average_Vote: "FanRate",
  PLAYER_NAME: "Nome del giocatore",
  Players: "Giocatori",
  Substitute: "Sostituti",
  Coach: "Allenatore",
  TO_UNLOCK_MATCH: "PER SBLOCCARE LA PARTITA",
  BUY_MATCH_BTN_TEXT: "Sblocca",
  TOKENS_VALUE: "FanCoins",
  SHARE_BTN: "CONDIVIDI",
  UNLOCK_MATCH: "Vuoi votare più partite? Sali di livello guadagnando punti!",
  INVITE_INFO:
    "Ciao, vorrei invitarti su Fan Rating, fai clic sul link e registra il tuo account.",
  LEVEL: "Livello",
  HURRY_UP_VOTE: "Sbrigati! Le votazioni si chiuderanno presto!",
  MATCH_RESULTS:
    "I risultati verranno visualizzati 24 ore dopo la fine della partita!",
  QUIZ: "QUIZ",
  SELECT_TEAM: "Seleziona Squadra",
  SELECT_YOUR_TEAM: "seleziona la tua squadra",
  CHANGE_TEAM: "cambia squadra",
  CHOOSE_YOUR_TEAM: "scegli la tua squadra",
  INDEX: "INDICE",
  VOTE_FOR_MATCHES: "PARTITE",
  SOMETHING_WENT_WRONG: "qualcosa è andato storto",
  REMOVE_ALL: "Rimuovi tutto",
  VERIFICATION_SUCCESS: "Il tuo account è stato verificato con successo.",
  VERIFICATION_FAILED: "Il tuo account è stato rifiutato.",
  GO: "Vai",
  EMAIL_VERIFICATION: "verifica email",
  WELCOME: "Benvenuto",
  toFanSerie: "su Fan Rating!",
  KICK_OFF: "Manca poco al fischio d'inizio",
  WHY_WAIT: "Ma perché aspettare?",
  CANCEL: "Annulla",
  OK: "ok",
  UPCOMING_MATCH: "PROSSIMA PARTITA!",
  VOTE_ENABLED: "Potrai votare questa partita quando sarà terminata!",
  Password_Success: "Password cambiata con successo!",
  VOTING_CONFIRMATION:
    "Vuoi confermare le tue pagelle per {{TEAMA}} e {{TEAMB}}? Non potrai più modificare i tuoi voti dopo aver confermato.",
  WINNERS: "GUARDA FAN WINNER",
  VERIFIED: "SEI VERIFICATO!",
  NOT_VERIFIED: "NON SEI VERIFICATO!",
  FAQ: "Consulta le FAQ",
  HOW_TO_PLAY: "Scopri come giocare",
  BECOME_TESTER: "Diventa subito un tester",
  SORRY_THIS_PAGE_IS_NOT_AVAILABLE:
    "Spiacenti, questa pagina non è disponibile.",
  THE_LINK_YOU_FOLLOWED_MAY_BE_BROKEN:
    "Il link che hai seguito potrebbe essere interrotto o la pagina potrebbe essere stata rimossa.",
  GO_BACK_TO_FANRATINGWEB: "Torna su FanRatingWeb",
  CONFIRM_REDEEM:
    "Sei sicuro di voler riscattare {{productName}}? Il codice verrà inviato alla mail che hai usato in fase di registrazione",
  GOALKEEPER: "PORTIERE",
  DEFENDER: "DIFENSORE",
  MIDFIELDER: "CENTROCAMPISTA",
  FORWARD: "ATTACCANTE",
  COACH: "ALLENATORE",
  SIGNUP_EMAIL: "Iscriviti con e-mail",
  INVITE_AND_EARN: "Invita amici",
  ADD_COMMENT: "Aggiungi un commento . . .",
  UNLOCK: "SBLOCCA",
  PASSWORD_MUST_BE_MINIMUM_OF_8_CHARACTERS:
    "La password deve essere di minimo 8 caratteri",
  CHOOSE_FILE: "Scegli un file",
  EIGHTEEN_PLUS: "Devi avere più di 13 anni per procedere!",
  FIRSTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
    "il nome deve essere di almeno 3 lettere",
  LASTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
    "il cognome deve essere di almeno 3 lettere",
  USERNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
    "il nome utente deve essere di almeno 3 lettere",
  Be_First_to_like: "Puoi essere il primo a mettere like",
  PROFILE_UPDATED: "Immagine del profilo aggiornata.",
  APPLE_WARN:
    "Sei già registrato con account Apple? Per accedere richiedi una nuova password.",
  BUY_MORE_TOKENS: "Acquista più FanCoins",
  SELECT_ONE_OPTION: "Si prega di selezionare un'opzione qualsiasi!",
  VALID_DATE: "Si prega di inserire una data valida",
  NOT_LEAP_YEAR: "La data inserita non è un anno bisestile",
  INVLAID_LEAP_YEAR: "Data dell'anno bisestile non valida",
  INVALID_MONTH: "Mese non valido",
  INVALID_YEAR: "Anno non valido",
  FUTURE_DATE: "Non puoi inserire una data futura",
  ALTEAST_EIGHTEEN: "Devi avere almeno 13 anni",
  AWARD_REDEEMED: "PREMIO RISCATTATO!",
  CONGRATULATIONS_YOU_JUST_EARNED_A_COIN:
    "Congratulazioni! Hai guadagnato un FanCoin!",
  OFFLINE_TITLE: "Sei in modalità offline",
  OFFLINE_SUB_TITLE: "La tua app è in modalità offline",
  OFFLINE_DESC:
    "Prova a controllare la tua connessione Internet o le impostazioni Wi-Fi",
  OFFLINE_REFRESH_BTN: "ricaricare",
  MATCH: "Incontro",
  POSITION: "Posizione",
  FAN_WINNERS: "Fan Winners",
  VOTE_NEW: "Voto",
  DEVICE_INFO1: "Non sai come installare Fan Rating sul tuo dispositivo?",
  DESCTOP_INFO1: "Non sai come installare Fan Rating sul tuo dispositivo?",
  DEVICE_INFO2: "Scopri come, toccando qua sotto",
  DESCTOP_INFO2: "Scopri come, cliccando qua sotto",
  DESCTOP_BTN_NAME: "Clicca qui",
  DEVICE_BTN_NAME: "Tocca qui",
  NEW_MENU_OPTION: "Installa Fan Rating",
  EARNED_MORE_TOKENS:
    "Non hai abbastanza FanCoins per questo premio. Guadagnane ancora oppure acquistali",
  TEASING_ROOM: "Sfottò community",
  TEASING_ROOM_TITLE: "Angolo dello Sfottò",
  CAPTION: "Didascalia",
  MEDIA: "FanRate",
  ADD_POST: "Sfotti",
  READY_TO_SEND: "PRONTO PER L’INVIO?",
  DELETE_POST: "Sei sicuro di voler eliminare questo post?",
  MY_POST: "I miei sfottò",
  POST_CAPTION: "Inserisci didascalia qui...",
  REPORT_POST: "Segnala post",
  REPORT_REASON: "Motivo",
  REASON_PLACEHOLDER: "Aggiungi motivo della segnalazione....",
  INCREASE_LEVEL: "Sali di livello",
  CHECK_EMAIL:
    "Grazie per aver riscattato questo premio, controlla la tua posta per il tuo codice.",
  ADD_POST_VALIDATION: "Aggiungi immagine o video",
  ADD_CAPTION_VALIDATION: "Aggiungi didascalia",
  NO_COMMENT:
    "Nessun commento disponibile in questo momento. Puoi essere il primo a lasciare un commento.",
  LEVEL_PRICE: "FanCoins necessari",
  INCREASE_LEVEL1: "Sali di livello",
  ENTER_REPORT: "Si prega di inserire il motivo",
  EDIT_POST: "Modifica post",
  UPLOAD_FAILED: "Impossibile caricare il file mkv. Seleziona mp4/webm",
  COMMENT_SCREEN_TITLE: "Commenti",
  MOST_COMMENTS: "Più commentata",
  MOST_LIKES: "Più like",
  MOST_RECENT: "Più recente",
  ORDER_BY: "Ordina per",
  TEAM_TAG: "Tag squadra",
  SELECT_TEAM_TAG: "Seleziona tag squadra",
  FIRST_POST:
    "Che silenzio qui, fai ridere gli altri Tifosi con il tuo primo sfottò",
  INVALID_FILE: "tipo di file non valido",
  UPLOAD_DOCUMENT: "CARICA DOCUMENTO",
  SAVE_DOCUMENT: "Salva documento",
  PLEASE_SELECT_FILE: "Si prega di selezionare il file",
  New_Token_key: "Sali di livello",
  showMore: "Mostra di più",
  reply: "Rispondere",
  ALL_VIDEOS: "Tutti i video",
  ALL_NEWS: "Tutte le news",
  LIKE: "Piace",
  ATTENTION: "ATTENZIONE!",
  VOTE_ALL_PLAYERS: "Esprimi un voto per tutti i giocatori! ",
  WELCOME_BACK_ONBOARD: "Bentornato a bordo!",
  SIGN_IN_WITH_EAMIL: "Accedi con email",
  WELCOME_TO_FAN_RATING: "Benvenuto in Fan Rating",
  BACK: "indietro",
  NOT_REGISTERED_YET: "Non sei ancora registrato? ",
  CREATE_AN_ACCOUNT: "Crea un Account!",
  JOIN_THE_COMMUNITY_OF_FOOTBALL_FANS: "Unisciti alla più grande community di Tifosi di calcio dove Sei tu il protagonista!",

  CONFIRM: "Conferma",
  CONTINUE_VOTE: "Conferma il voto",
  NOTE_TWO_TEAMS: "Hai 2 squadre e 2 pagelle da votare",
  INSTALL_APP_ON_IPHONE: "Installa in iPhone",
  INSTALL_APP_ON_ANDROID: "Installa in Android",

  FAN_COINGS_LEVET_UP_CONFIRM_MESSAGE: "Necessiti {level_price} FanCoins per salire di livello. Sei sicuro di voler procedere?",
  FAN_SUBSCRIBER_TV: "Abbonato TV",
  FAN_SEASON_TICKET: "Abbonato Stadio",
  FAN_OCCA: "Occasionale",
  PROFILE_UPDATE_MESSAGE: "Il tuo profilo è stato modificato",
  Phone: "Telefono",
  ENTER_YOUR_PHONE: "Inserisci il tuo telefono.",
  // new words 3/10/2023
  FUN_VERSE: 'FunVerse',
  REGISTER: 'Registrati'
};
