export const SpLanguage = {
    TEAMLIST_TITLE: "SELECCIONA TU EQUIPO",
    NOTIFICATION: "Notificación",
    TEAMLIST_DESC:
        "Recuerda que ya no podrás cambiarlo, será el único equipo por el que votarás",
    TEAMLIST_DESC2: "gratis y sobre el que recibirás novedades",
    NEXT: "Vamos",
    NEXT_2: "Próximo",
    TIFA: "ANIMA",
    RATE_IT: "VOTA",
    WIN: "GANA",
    ALL: "Todos",
    CURRENT: "En progreso",
    PAST: "Mis Boletas",
    RATE: "VOTA",
    VOTE: "Vota",
    VIEW: "Mira",
    ACHIEVEMENTS: "GANA",
    PRIME_AMAZON: "PREMIOS AMAZON",
    PARTNERS_PRIZES: "PREMIOS PARTNER",
    LIMITED_AVAILABILITY: " DISPONIBILIDAD LIMITADA",
    VIEW_ALL: "Mira todos",
    FORGOT_PASSWORD_CAPITAL: "?",
    FORGOT_PASSWORD: "¿CONTRASEÑA OLVIDADO?",
    Forgot_Password: " ¿ Contraseña olvidada?",
    NEW_PASSWORD: "Nueva contraseña ",
    CONFIRM_NEW_PASSWORD: "Confirmar nueva contraseña",
    SAVE_PASSWORD: "Guardar contraseña",
    LOGIN: "Iniciar sesión",
    EDIT_PROFILE: "Editar perfil",
    SIGN_OUT: "Desconectar",
    SIGN_IN: "Iniciar",
    SIGN_IN_CAPITAL: "INICIAR",
    SIGN_UP: "REGISTRAR",
    YOUR_TOKENS: "Mis FanCoins",
    SIGN_UP_CAPITAL: "REGISTRAR",
    TOKEN: "FanCoins",
    POINTS: "Puntos",
    EMAIL: "E-mail",
    PASSWORD: "Contraseña",
    OR: "O",
    SIGN_IN_WITH_APPLE: "Iniciar sesión con Apple",
    SIGN_IN_WITH_FACEBOOK: "Iniciar sesión con Facebook",
    SIGN_IN_WITH_GOOGLE: "Iniciar sesión con Google",
    SIGN_UP_WITH_APPLE: "Registrarse con Apple",
    // SIGN_Up_WITH_FACEBOOK: "Registrarse con Facebook",
    // SIGN_Up_WITH_GOOGLE: "Registrarse con Google",
    NO_ACCOUNT: "¿Todavía no tienes una cuenta?",
    HAVE_ACCOUNT: "¿Tienes una cuenta?",
    FIRST_NAME: "Nombre",
    LAST_NAME: "Apellido",
    GENDER: "Sexo",
    DATE_OF_BIRTH: "Fecha de nacimiento",
    USERNAME: "Nombre de usuario",
    CREATE_ACCOUNT: "Crear cuenta",
    SIGN_UP_WITH_FACEBOOK: " Suscribir con Facebook",
    SIGN_UP_WITH_GOOGLE: "Suscribir con Google",
    MALE: "Masculino",
    FEMALE: "Femenino",
    OTHER: "Otro",
    THANK_YOU_FOR_SUBMITTING: "GRACIAS POR ENVIAR",
    PASSWORD_CHANGE_SUCCESSFULY: "CAMBIO DE CONTRASEÑA CON ÉXITO",
    PASSWORD_CHANGE_SUCCESSFUL: "CAMBIO DE CONTRASEÑA CON ÉXITO",
    PREVIOUS: "Anterior",
    SUBMIT: "Enviar",
    FINISH: "Ver resultado",
    SKIP: "Saltar",
    QUIZ_INSTRUCTIONS: "INSTRUCCIONES DEL QUIZ",
    QUIZ_RESULT: "TU RESULTADO",
    YOUR_SCORE: "TU PUNTUACIÓN",
    EARNED_TOKENS: "FANCOINS GANADOS",
    CLOSE: "Cerrar",
    FISCAL_CODE: "NIF",
    EDUCATION: "Educación",
    CITY: "Ciudad",
    PROFESSION: "Profesión",
    SAVE_PROFILE: "Guardar perfil",
    YOUR_PROFILE: "Tu perfil",
    CHANGE_PASSWORD: "CAMBIA CONTRASEÑA",
    CHEERS: "ANIMAR",
    STREAMS: "LIVE",
    FAN_RATING_TV: "FAN RATING TV",
    NEWS: "BLOG",
    FILTER_BY: "Filtrado por",
    PRIVACY_POLICY: "Privacy",
    TERMS_AND_CONDITION: "Términos y condiciones",
    MISSION: "Mission",
    HELP: "Reglamentos y FAQ",
    CONTACT_US: "Contáctenos",
    RANKING: " Clasificación",
    BUY_PACKAGE: "Comprar el paquete",
    THANK_YOU_FOR_REVIEW: "GRACIAS POR ENVIAR",
    THANK_YOU_FOR_VOTING:
        "¡Gracias por enviarnos! Tu puntuación estará disponible 24 horas después de que finalice el partido. ¡Vuelve a consultar!",
    COUNTRY: "País",
    WATCH_ON: "Ver en la tele",
    GO_TO_SAN_SIRO_STADIUM: "Entradas estadio",
    GIFT_CARD: "Gift Card",
    DISCOUNT_CODES: "Códigos descuento",
    PRIME_SPECIAL: "Premios Especiales",
    GOAL: "Goles",
    AVERAGE_FAN_RATING: "FanRate",
    PLAYED_MATCHES: " Partidos jugados ",
    RANK: "Clasificación",
    DESCRIPTION: "Descripción",
    ACCEPT_TERMS_AND_CONDITION: "Aceptar terminos y condiciones",
    CONGRATULATION: "Felicidades",
    YOUR_RATE_CARD: "MIS BOLETÍNS",
    REDEEM_FOR_TOKENS: " Canjear con Fan Coins",
    LIVE: "LIVE",
    POSTED_ON: "Publicado en",
    MESSAGE: "Mensaje",
    IN_PROGRESS: "En progreso",
    CONCLUDED: "Mis Boletìns",
    ABOUT_US: "About Us",
    MY_TEAM: "Mi equipo",
    FAN: "Admirador",
    TV_SUBSCRIBER: "Suscriptor tele",
    STADIUM_SUBSCRIBER: "Suscriptor estadio",
    OCCASIONAL: "Ocasional",
    JOB_LEVEL: "Profesión",
    YES_LETS_START_CHEERING: "Sí, empecemos a animar",
    NO_I_WANT_TO_CHANGE: "No, quiero cambiar",
    Look_at_all: "Mirarlo todo",
    Share_review: "Comparte los votos con tus amigos",
    Find_out: "Descubre si ganaste entre",
    remaining: "restante",
    how_to_play: "¿Cómo jugar?",
    UPLOAD_A_PHOTO: "SUBE UNA FOTO",
    SAVE_PHOTO: "Salvar Foto",
    GAMES_PLAYED: "Partidos jugados",
    NATIONALITY: "Nacionalidad",
    HEIGHT: "Altura",
    WEIGHT: "Peso",
    I_AM_18_YEARS_OLD: "Tengo 13 años",
    REQUIRED_TO_MAKE_IN_APP_PURCHASES_AND_ACCESS_THE_REWARDS_CATALOG:
        "Requerido para hacer compras y acceder al Catálogo",
    SELECT_YOUR_HEART_TEAM: "ELIGE TU EQUIPO DE CORAZÓN",
    QUIZ_CONGRATULATIONS: "¡Felicitaciones, eres el ganador del Quiz! ¡Respondiste todas las preguntas correctamente!",
    QUIZ_TRY_AGAIN:
        "Tienes que prepararte un poco más pero no te preocupes, ¡puedes compensarlo en el próximo quiz!",
    CONGRATULATIONS: "¡Felicidades!",
    BETTER_LUCK_NEXT_TIME: "Próxima vez tendrás más suerte",
    INVITE_A_FRIEND_AND_RECEIVE_25_TOKENS:
        "invita a un amigo y obtén 25 FanCoins",
    INVITE_FRIENDS_DESCRIPTION:
        "Puede invitar a un amigo a registrarse en Fan Rating y recibir 25 FanCoins. Recuerde, recibirá las FanCoins una vez que el usuario complete el registro a través del enlace de invitación.",
    INVITE_A_FRIEND: "Invita a un amigo",
    INVITE_AND_REFER: "Invita a un amigo",
    BUY_TOKENS: "Compra FanCoins",
    TOKENS: "FanCoins",
    MAKE_A_PAYMENT: "Realizar un pago",
    TRANSACTION_LIST: "Lista de transacciones",
    VOTE_other_matches: "VOTA por otros partidos",
    LIKES: "Mi Piace",
    SURVEY_INSTRUCTIONS: "INSTRUCCIONES ENCUESTA",
    SURVEY: "ENCUESTA",
    SURVEY_COMPLETED: "¡Gracias! Tu reseña ha sido recibida.",
    RESET_PASSWORD: "Restablecer contraseña",
    WARNING: "¡Advertencia!",
    OOPS: "Oops!",
    ALERT: "¡Alerta!",
    Something_went_wrong: "Algo salió mal",
    SUCCESS: "¡Éxito!",
    ENTER_YOUR_EMAIL: "Inserte tu correo electrónico",
    ENTER_YOUR_PASSWORD: "Ingresa tu contraseña",
    ENTER_YOUR_FIRST_NAME: "Inserte su nombre",
    ENTER_VALID_FIRSTNAME: "Por favor ingrese un nombre valido",
    ENTER_YOUR_LAST_NAME: "Ingresa el apellido",
    ENTER_VALID_LASTNAME: "Por favor ingrese un apellido válido",
    ENTER_YOUR_USER_NAME: " Ingrese tu nombre de usuario",
    ENTER_VALID_USERNAME: "Por favor ingrese un nombre de usuario válido",
    ENTER_YOUR_DATE_OF_BIRTH: "Introduzca su fecha de nacimiento",
    ENTER_YOUR_GENDER: "Ingrese su género",
    PLEASE_ACCEPT_TERMS_AND_CONDITIONS:
        "Por favor, acepte los términos y condiciones",
    PLEASE_SELECT_IF_YOU_ARE_18: "Seleccione si tiene al menos 18 años",
    PASSWORD_MUST_BE_BETWEEN_8_AND_12:
        "La contraseña debe tener al menos 8 caracteres",
    BOTH_PASSWORDS_MUST_BE_SAME: "Ambas contraseñas deben ser iguales",
    PLEASE_ENTER_VALID_EMAIL_ADDRESS: "Ingrese una dirección de correo electrónico válida",

    PLEASE_ENTER_VALID_BIRTHDATE:
        "Ingresa una fecha de nacimiento valida",
    SELECT_YOUR_GENDER: "Selecciona tu género",
    SELECT_YOUR_JOB_LEVEL: "Selecciona tu trabajo",
    SELECT_YOUR_EDUCATION: "Selecciona tu estudios",
    SELECT_AN_OPTION: "Selecciona una opción",
    SELECT_YOUR_CITY: "Selecciona tu ciudad",
    SELECT_YOUR_COUNTRY: "Selecciona tu pais",
    No_cards: "No hay tarjeta disponible",
    Use_default_card: " Usar esta tarjeta por defecto",
    CARD_LIST: "LISTA DE TARJETAS",
    ADD_CARD: "INSERTAR",
    Add_New_Card: "Añadir nueva tarjeta",
    Pay: "Pagar",
    Card_Details: "Detalles de tarjeta",
    ACCEPT_TC: "Aceptar terminos y condiciones",
    Delete_Message: "¿Está seguro de que desea eliminar esta tarjeta?",
    Logout_Message: "¿Seguro que quieres salir?",
    SORRY_NO_DATA_FOUND: "¡Lo sentimos, no se encontraron datos!",
    NAME: "Nombre",
    REMOVE_ALL_NOTIFICATION: "¿Está seguro de que desea eliminar todas las notificaciones?",
    Average_Vote: "FanRate",
    PLAYER_NAME: "Nombre jugador",
    Players: "Jugadores",
    Substitute: "Sustitutos",
    Coach: "Mister",
    TO_UNLOCK_MATCH: "PARA DESBLOQUEAR EL JUEGO",
    BUY_MATCH_BTN_TEXT: "desbloquear",
    TOKENS_VALUE: "FanCoins",
    SHARE_BTN: "COMPARTIR",
    UNLOCK_MATCH: "¿Quieres calificar más juegos? ¡Sube de nivel ganando puntos!",
    INVITE_INFO:
        " Hola, me gustaría invitarlo a Fan Rating, haga clic en el enlace y registre su cuenta.",
    LEVEL: "Nivel",
    HURRY_UP_VOTE: "¡Date prisa! ¡La votación se cerrará pronto!",
    MATCH_RESULTS:
        "¡Los resultados se mostrarán 24 horas después del final del partido!",
    QUIZ: "QUIZ",
    SELECT_TEAM: "Selecciona equipo",
    SELECT_YOUR_TEAM: "selecciona tu equipo",
    CHANGE_TEAM: "cambiar equipo",
    CHOOSE_YOUR_TEAM: "elige tu equipo",
    INDEX: "ÍNDICE",
    VOTE_FOR_MATCHES: "PARTIDOS",
    SOMETHING_WENT_WRONG: "algo salió mal",
    REMOVE_ALL: "Eliminar todo",
    VERIFICATION_SUCCESS: "Su cuenta ha sido verificada con éxito.",
    VERIFICATION_FAILED: "Tu cuenta ha sido rechazada.",
    GO: "Vamos",
    EMAIL_VERIFICATION: "verificar correo electrónico",
    WELCOME: "Bienvenidos",
    toFanSerie: "en Fan Rating!",
    KICK_OFF: "Ya casi es el pistoletazo de salida",
    WHY_WAIT: "¿Pero por qué esperar?",
    CANCEL: "Cancelar",
    OK: "ok",
    UPCOMING_MATCH: "¡PRÓXIMO PARTIDO!",
    VOTE_ENABLED: "¡Podrás votar este juego cuando esté terminado!",
    Password_Success: "¡Contraseña cambiada correctamente!",
    VOTING_CONFIRMATION:
        "¿Quiere confirmar tus votos para {{TEAMA}} y {{TEAMB}}? Ya no podrás editar tus calificaciones después de confirmar.",
    WINNERS: "MIRA FAN WINNER",
    VERIFIED: "¡ESTÁS VERIFICADO!",
    NOT_VERIFIED: "¡NO ESTÁS VERIFICADO!",
    FAQ: "Consulta las preguntas frecuentes",
    HOW_TO_PLAY: "Aprende cómo jugar",
    BECOME_TESTER: "Conviértete en un probador ahora",
    SORRY_THIS_PAGE_IS_NOT_AVAILABLE:
        "Lo sentimos, esta página no está disponible.",
    THE_LINK_YOU_FOLLOWED_MAY_BE_BROKEN:
        "El enlace que siguió puede estar roto o la página puede haber sido eliminada.",
    GO_BACK_TO_FANRATINGWEB: " Regresa a FanRatingWeb",
    CONFIRM_REDEEM:
        "¿Está seguro de que desea canjear {{productName}}? El código se enviará al correo electrónico que utilizó durante el registro",
    GOALKEEPER: "PORTERO",
    DEFENDER: "DEFENSOR",
    MIDFIELDER: "CENTRAL",
    FORWARD: "DELANTERO",
    COACH: "ENTRENADOR",
    SIGNUP_EMAIL: "Ingresa con e-mail",
    INVITE_AND_EARN: "Invitar a amigos",
    ADD_COMMENT: "Añadir un comentario . . .",
    UNLOCK: "DESBLOQUEAR",
    PASSWORD_MUST_BE_MINIMUM_OF_8_CHARACTERS:
        "La contraseña debe tener al menos 8 caracteres",
    CHOOSE_FILE: "Escoge un archivo",
    EIGHTEEN_PLUS: "¡Debes tener más de 18 años para continuar!",
    FIRSTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "el nombre debe tener al menos 3 letras",
    LASTNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "el apellido debe tener al menos 3 letras",
    USERNAME_SHOULD_BE_OF_ATLEAST_3_LETTERS:
        "el nombre de usuario debe tener al menos 3 letras",
    Be_First_to_like: "Sé el primero en dar me gusta",
    PROFILE_UPDATED: "Imagen de perfil actualizada.",
    APPLE_WARN:
        "¿Ya estás registrado con una cuenta de Apple? Para acceder, solicita una nueva password.",
    BUY_MORE_TOKENS: " Compra más FanCoins",
    SELECT_ONE_OPTION: "¡Seleccione cualquier opción!",
    VALID_DATE: "Por favor introduzca una fecha valida",
    NOT_LEAP_YEAR: "La fecha ingresada no es un año bisiesto",
    INVLAID_LEAP_YEAR: "Fecha de año bisiesto no válida",
    INVALID_MONTH: "Mes inválido",
    INVALID_YEAR: "Año no válido",
    FUTURE_DATE: "No puede ingresar una fecha futura",
    ALTEAST_EIGHTEEN: "Debes tener al menos 13 años",
    AWARD_REDEEMED: "¡PREMIO CANJADO!",
    CONGRATULATIONS_YOU_JUST_EARNED_A_COIN:
        "¡Felicitaciones! ¡Te has ganado un FanCoin!",
    OFFLINE_TITLE: "Estás en modo fuera de línea",
    OFFLINE_SUB_TITLE: "Su aplicación está en modo fuera de línea",
    OFFLINE_DESC:
        "Intenta verificar tu conexión a Internet o la configuración de Wi-Fi",
    OFFLINE_REFRESH_BTN: "Recargar",
    MATCH: "Partido",
    POSITION: "Posición",
    FAN_WINNERS: "Fan Winners",
    VOTE_NEW: "Voto",
    DEVICE_INFO1: "¿No sabes cómo instalar Fan Rating en tu dispositivo?",
    DESCTOP_INFO1: "¿No sabes cómo instalar Fan Rating en tu dispositivo?",
    DEVICE_INFO2: "Descubra cómo, tocando a continuación",
    DESCTOP_INFO2: "Descubre cómo, haciendo clic abajo",
    DESCTOP_BTN_NAME: "Haga clic aquí",
    DEVICE_BTN_NAME: "Pulse aquí",
    NEW_MENU_OPTION: "Instalar Fan Rating",
    EARNED_MORE_TOKENS:
        "No tienes suficientes FanCoins para este premio. Gana más o cómpralos",
    TEASING_ROOM: "Broma community",
    TEASING_ROOM_TITLE: "Angulo de burlas",
    CAPTION: "Subtítulo",
    MEDIA: "Voto Fans",
    ADD_POST: "Publicar",
    READY_TO_SEND: "¿LISTO PARA ENVIAR?",
    DELETE_POST: "¿Estás seguro de que quieres eliminar esta publicación?",
    MY_POST: "Mis burlas",
    POST_CAPTION: "Insertar título aquí...",
    REPORT_POST: "Reportar publicacion",
    REPORT_REASON: "Razón",
    REASON_PLACEHOLDER: "Agregar motivo para informar...",
    INCREASE_LEVEL: "Elevar nivel",
    CHECK_EMAIL:
        "Gracias por canjear esta recompensa, revise su bandeja de entrada para obtener su código.",
    ADD_POST_VALIDATION: "Agregar imagen o video",
    ADD_CAPTION_VALIDATION: "Añadir un subtitulo",
    NO_COMMENT:
        "No hay comentarios disponibles en este momento. Sea el primero en dejar un comentario.",
    LEVEL_PRICE: "FanCoins necessarios",
    INCREASE_LEVEL1: "ELEVAR NIVEL",
    ENTER_REPORT: "Por favor ingrese el motivo",
    EDIT_POST: "Editar publicaciones",
    UPLOAD_FAILED: "Error al cargar el archivo mkv. Seleccione mp4/webm",
    COMMENT_SCREEN_TITLE: "Comentarios",
    MOST_COMMENTS: "Más comentado",
    MOST_LIKES: "Más Me gusta",
    MOST_RECENT: "Más reciente",
    ORDER_BY: "Ordenar por",
    TEAM_TAG: "Tag equipos",
    SELECT_TEAM_TAG: "Seleccione tag equipo",
    FIRST_POST:
        "Qué silencio aquí, haz reír a otros Fans con tu primera provocación",
    INVALID_FILE: "tipo de archivo invalido",
    UPLOAD_DOCUMENT: "CARGAR DOCUMENTO",
    SAVE_DOCUMENT: "Guardar documento",
    PLEASE_SELECT_FILE: "Seleccione el archivo",
    New_Token_key: "Elevar nivel",
    showMore: "Mostrar más",
    reply: "Responder",
    ALL_VIDEOS: "Todos los videos",
    ALL_NEWS: "Todas las noticias",
    LIKE: "Gusta",
    ATTENTION: "¡ATENCIÓN!",
    VOTE_ALL_PLAYERS: "¡Vota por todos los jugadores!",
    WELCOME_BACK_ONBOARD: "¡Bienvenido de nuevo a bordo!",
    SIGN_IN_WITH_EAMIL: "Iniciar sesión con correo electrónico",
    WELCOME_TO_FAN_RATING: "Bienvenido en Fan Rating",
    BACK: "Atrás",
    NOT_REGISTERED_YET: "¿Todavía no estas registrado?",
    CREATE_AN_ACCOUNT: "¡Crea una cuenta!",
    JOIN_THE_COMMUNITY_OF_FOOTBALL_FANS: "¡Únete a la comunidad más grande de fanáticos del fútbol donde tú eres el protagonista!",

    CONFIRM: "Confirmado",
    CONTINUE_VOTE: "Confirma tu voto",
    NOTE_TWO_TEAMS: "Tienes 2 equipos y 2 boletas de calificaciones para votar",
    INSTALL_APP_ON_IPHONE: "Instalar en iPhone",
    INSTALL_APP_ON_ANDROID: "Instalar en Android",

    FAN_COINGS_LEVET_UP_CONFIRM_MESSAGE: "Necesitas {level_price} FanCoins para subir de nivel. ¿Estas seguro que deseas continuar?",
    FAN_SUBSCRIBER_TV: "Suscriptor TV",
    FAN_SEASON_TICKET: "Suscriptor estadio",
    FAN_OCCA: "Ocasional",
    PROFILE_UPDATE_MESSAGE: "Tu perfil ha sido cambiado",
    Phone: "Teléfono",
    ENTER_YOUR_PHONE: "Ingresa tu teléfono.",
    // new words 3/10/2023
    FUN_VERSE: 'FunVerse',
    REGISTER: 'Registro'
}